DELETE FROM site_web_lugar;
DELETE FROM site_web_mujer;
DELETE FROM site_web_publicacion;
DELETE FROM site_web_ejerce;
DELETE FROM site_web_evento;

INSERT INTO site_web_lugar(id,region,provincia,distrito) VALUES
	(1,"Cusco","Cusco","Cusco"),
	(2,"Cusco","Canas","Layo"),
	(3,"Cusco","Quispicanchi","Huaro");

INSERT INTO site_web_mujer(id,nombre,apellido,lugar_id,fecha_nacimiento,fecha_defuncion,trayectoria,link_imagen,Contacto,coordx,coordy,Entrevista) VALUES
	(1,"Adriana Hiromi ","Cule Vargas",1,"20/04/1996",NULL,"Adriana Cule es una artista visual y retratista profesional. Se desenvuelve en el terreno del diseño gráfico, el modelado análogo y digital, el desarrollo de personajes pintorescos y la creación de cuentos cortos. En sus obras busca que las perspectivas y composición interactúen con el espectador exagerando las formas.
Ha participado en diferentes proyectos, muestras artísticas, diferentes campañas y producciones entre ellas la inauguración de Saga Falabella en Cusco, la filmación de Transformers en Cusco y la iniciativa de “Hagamos un Perú que de gusto” de Inca Kola.
Ilustro el cuento “El zorro y el cóndor” de Maximo Ccama, realizo el libro de cuentos “Sueño Índigo” y los cómics “Pasado” y “Colores”.","img/Mujer_1.jpg","yozoh2004@gmail.com
","-13.518936101916335 ","-71.98050471302038","https://www.youtube.com/embed/Nz-d6tKw4wA"),
	(2,"Ana Maria","Milla Hurtado",1,"15/06/1977",NULL,"Cusqueña de nacimiento, administradora de formación. Desde el 2003 ha participado como gestora cultural como productora de eventos y posteriormente la primera agenda cultural virtual, Agenda Cusco. Tiene trayectoria de empresaria turística del 2002, como diseñadora y productora de eventos durante 9 años. Ha participado en numerosos recitales, como poeta y productora. Actualmente dirige el Planetarium Cusco, centro de interpretación cultural, planetario y observatorio, lugar donde se difunde la ciencia, el universo y la astronomía cultural de los inkas. Es también feliz de mamá de tres y artista floral","img/Mujer_2.jpg","anamaria@planetariumcusco.com","-13.5219062351864","-71.95797387209109","https://www.youtube.com/embed/KezcLgAdhTA"),
	(3,"Angela María"," Concha Pacheco",1,"06/06/1980",NULL,"Angela M. Concha es licenciada en Historia por la Universidad Nacional de San Antonio Abad del Cusco. Magister en Historia de América Latina, Mundos Indígenas por la Universidad Pablo de Olavide en Sevilla-España, y candidata a Doctora en Historia y Estudios Humanísticos: Europa, América, Arte y Lenguas por la misma Universidad. Con experiencia en trabajos sobre patrimonio documental y monumental (templos, casonas coloniales, centros arqueológicos y archivos históricos), en labores de conservación, catalogación e investigación. Docente de la Universidad de Salamanca (España)/ International Studies Abroad (ISA-Cusco) y de la Universidad Nacional de San Antonio Abad del Cusco. 
","img/Mujer_3.jpg","angelamaria11y6@gmail.com","-13.5215231640725","-71.95862120997890","https://www.youtube.com/embed/v7WSLHeSR44"),
	(4,"Gladys","Conde Camargo",1,"07/03/1982",NULL,"Poeta y cantautora. Ha sido acompañante musical en centros de educación inicial de Cusco. También facilitadora de talleres en torno del arrullo para madres gestantes, madres adolescentes, abuelos, recien nacidos, profesores, médicos y enfermeros.
Obtuvo una mención honrosa en poesía por el Premio Regional de Cultura de Cusco (2006), publicándose sus poesías “Antología Poética del Cusco” INC (2007), “Juego y silencio” Editorial Saqra (2009), “Lliqlla. El Canto de la abuela” (2020) por el Fondo Editorial SM. Sus composiciones musicales que son poesías hechas canción que se encuentran en los discos ”Zorrito Ramón” (2011), “Intiwawacha” (2012); “El vuelo de katari” (2013), “Wanamey: Árbol de vida” (2017). “Wawa Bebé” (2021). Ha venido desarrollando proyectos integrales como “Tejedores del sonido”, donde se enseña a hilar acompañadas del recurso del canto, “Conciertos de arrullo para bebés” y los círculos de expresión “El Cuerpo de la Voz”, para víctimas que han callado la violencia y “Voces y cantos para el arrullo” para fortalecer los vínculos afectivos de la familia con el bebé. Últimamente fue facilitadora del programa “Cartas y arrullos desde adentro” en el Penal de Qenqoro de Cusco a través del proyecto atravesando Muros liderado por Anahí Araoz. Actualmente viene componiendo cantos para obras escénicas y cine. Pueden ser apreciadas en “ Lliqllas infinitas” (2021), bajo la dirección Huandy Laguna y “K´anchay” (2022), que son cuentos salvavidas para niños y niñas bajo la inspiración de Luz Saenz y Adalid Rondan.
","img/Mujer_4.jpg","condeinfinito@hotmail.com","-13.522798","-71.97945447901128","https://www.youtube.com/embed/myEpMpTkVSY"),
	(5,"Natalya Eddem ","Lizarraga Conchatupa",1,"07/10/1982",NULL,"Con experiencia laboral desde el 2003 hasta la actualidad. Natalya Lizarraga ha trabajado en diferentes proyectos artísticos individuales y colectivos. Su trabajo consiste en estéticas como el surrealismo, surrealismo narrativo, que se ven reflejados en trabajos como: “Dulcinea”, “Huida a Egipto“, “Nativo“, parte del proyecto “Memoria 2014“ que constó de 4 exhibiciones realizadas en diferentes Centros Culturales del Cusco-Perú; otros trabajos con enfoque mayormente ecológico, de diferentes especies emblemáticas o en peligro de extinción a nivel nacional o internacional tenemos “Tigrillo“ 2015. Tambien en sus exposiciones se han enfocado en la cultura viva como son tradiciones orales, con obras como con la muestra realizada en la casa cultural Cusco-Perú , 2016. Otras expresiones artisticas que revalorando tradiciones y creencias mortuarios que se tienen en la actualidad que provienen desde la cosmovisión precolombina, con obras como “El condenado“, “Aparición“, “Ofrendas“ . Sobre mitos y leyendas, a nivel nacional e internacional nos deleita con obras como “El Minotauro“ 2004. Natalia Lizarraga ha tenido exposiciónes individuales y colectivas en el Perú como en el extranjero en paises como: México, Bruselas, Alemania y Estados Unidos. En el campo de la ilustración ha participando en proyecto como la publicación “Cuentos Aguarunas“ del Centro Guamán Poma de Ayala Cusco en 2010, tambien trabajo en el libro-cancionero “LLIQLLA“2021 con la Editorial SM Perú y colaborando en la portada del Álbum Musical Lliqlla de la misma cantautora Gladys Conde, Cusco, 2021.","img/Mujer_5.jpg","milimetricoinfinito@gmail.com","-13.522533","-71.966346","https://www.youtube.com/embed/-Q8TvP0NMos"),
	(6,"Antonieta","Conde Marquina",2,"10/05/1981",NULL,"Maestra y gestora intercultural. Magíster en Educación Intercultural Bilingüe. Madre, mujer e hija del ancestral Pueblo Quechua Kʼana de Layo, Cusco. Sus áreas de interés son: Intraculturalidad e interculturalidad, investigación y gestión intercultural en temáticas socioculturales, socioeducativas, sociolingüísticas y ciudadanía intercultural vinculados a los pueblos indígenas. En su trayectoria de proyección sociocultural, académica y de vida ha realizado publicaciones, presentaciones, actividades formativas y labores profesionales, con énfasis en lo testimonial, desde el enfoque intercultural dentro y fuera del Perú. Editora y correctora independiente, en quechua y castellano, de investigaciones científico sociales, literarias e informativas (desde 2003 hasta la actualidad). Es alumni/exbecaria de la Fundación Ford, FLACSO Argentina e Ibercultura Viva, FILAC y AECID.","img/Mujer_6.jpg","antonietacondemarquina@gmail.com","-14.48242077795887","-71.15427871932138","https://www.youtube.com/embed/aXVNtofplSk"),
	(7,"Lucy Magály","Fernández Medina",1,"24/11/1980",NULL,"Nació en la mítica ciudad del Cusco. Lugar en el que vivió hasta terminar sus estudios en la Universidad Andina (UAC). Es escritora, profesora de español como lengua extranjera y licenciada en Turismo. Ha llevado talleres de narrativa y escritura creativa en el Centro Cultural de la Pontificia Universidad Católica del Perú (PUCP), y durante varios años asistió a talleres con el escritor Alonso Cueto. El 2016 participó en la “Antología de microrrelatos eróticos II” de la editorial Altazor. El 2018 publica “Rojo” su primera novela de la mano con la editorial Forjadestino.
Cuenta la historia de una joven, quien es obligada a casarse con un rico y cruel hacendado a inicios de los años 30. 
El 2020 su novela “Otra selva para Mercedes” fue ganadora de los Estímulos Económicos para la Cultura (Apoyo a la Producción Editorial Peruana). Aquí narra las vicisitudes de una mujer en el ambiente hostil y genocida de la época del caucho. Y su cuento “Un trozo desprendido de la luna”, inspirado en Tomasa de Amat y García Mancebo será publicado en “21 Relatos sobre mujeres que lucharon por la independencia del Perú” de Petroperú.
","img/Mujer_7.jpg","artemisa_30@hotmail.com","-13.5367","-71.9049","https://www.youtube.com/embed/KKCDJW7P2P8"),
	(8,"Lenyan","Veka Pantigoso",1,"23/03/1989",NULL,"Poeta de Cusco, Docente de Arte, artista visual, actriz, performer y gestora cultural. Miembro- directora en Nina Warmikuna (2019) directora creativa en Guíame Sur Arequipa Organización Cultural, Lenyan Veka Art Concept, gestora en Cuéntame Poesía Online -En la voz del poeta (2020-2021). Ganadora del primer lugar del Concurso Literario La Copa de Doce Ángulos en la categoría de poesía (Arequipa, 2016), Mención honrosa en el festival de poesía Qosqo Tikarinanpaq, poemario Danzan las aves (2020). Finalista selección Video Raymi, categoría Video Arte muestra Universidad de Bellas Artes Granada (2018). 
Ha participado y sido antologada dentro y fuera de Perú, exponente en muestras multidisciplinarias io virtuales (2016-2022) (Perú, Bolivia, Chile, Ecuador, México y España). Organizadora y gestora del XXIII Festival de Poesía del Sur Andino” Enero en la Palabra”, Escape poético, Desaparición de la distancia (2020), Recital Poesía Amorosa (2019) Ciudad poética en el ombligo del mundo (2020) entre otros.","img/Mujer_8.jpg","lenyanvk@gmail.com","-13.5190517604757","-71.98053057","https://www.youtube.com/embed/tyrHBmP8MF0"),
	(9,"Emperatriz","Escalante Gutiérrez",1,"14/07/1942",NULL,"Realizo su estudios escolares en Educandas, sus estudios universitarios los realizó en la Universidad Nacional de San Antonio Abad del Cusco, en la Facultad de Educación, especialidad de Lengua y Literatura, a la par estudió en la Escuela Superior de Bellas Artes “Diego Quispe Ttito” de Cusco, especialidad de Dibujo y Pintura. Integró el Teatro Experimental Universitario de Cusco (TEUC), sus primeras publicaciones aparecen en revistas de esos años, como Maccana, órgano de la Federación Universitaria de Cusco (1966), y participó en exposiciones pictóricas. Posteriormente, junto a sus hermanas María Olinda y Carmen, integró la Agrupación Cultural René Ramírez Lévano (ACRRL) que desarrolló actividad cultural durante toda la década de 1970. Allí fue responsable del departamento de literatura, publicó cuentos, artículos y escribió libretos de teatro. Allí también formó un hogar con el músico y ensayista Pablo Ojeda Vizcarra, líder de ese grupo autónomo de artistas e intelectuales con pasión por el arte y compromiso social. Fue profesora contratada en Pucyura (provincia de Anta), en Acomayo y en el distrito de San Jerónimo. Ya como profesora nombrada, dedicó varios años a la enseñanza en el colegio de Maras, el colegio agropecuario Charcahuaylla de Urubamba, y finalmente en la ciudad del Cusco, en el Colegio Real “San Francisco de Borja”, donde culminó su labor docente, cesando luego de haber dedicado toda una vida a formar varias generaciones de jóvenes, a quienes alentó a interesarse por la literatura, la investigación y la cultura andina.
Esa combinación de trabajo literario y pedagógico le llevó a ganar varios premios: Obtuvo el segundo lugar en el concurso de letras para el Himno del colegio Garcilaso (1977), el tercer lugar en el Premio Fomento a la Cultura, categoría cuento, organizado por la Municipalidad del Cusco (1982), el segundo lugar en los II Juegos Florales Magisteriales de la Región Inka con el cuento “Los pastorcitos” (1990), mención honrosa en el género ensayo en los III Juegos Florales Magisteriales de la Región Inka (1991), con su propuesta “Talleres de lectura y redacción: ensayo pedagógico de experiencia didáctica en la enseñanza”. Fue finalista en el concurso de cuentos en quechua organizado por la Asociación Pukllasunchis (2000), y obtuvo mención honrosa en el Premio Regional de Cultura del INC, categoría cuento en quechua (2006). 
Casi la totalidad de su obra está dedicada al público infantil, a los estudiantes. Por eso también, su trabajo teatral y en artes plásticas los plasmó en talleres vacacionales, especialmente en la década del 2000, en la Asociación Roberto Ojeda Campana. Esos años también, junto a sus hermanas María Olinda Escalante (filósofa) y Carmen Escalante (antropóloga), integró la Asociación de Escritoras del Cusco.
","img/Mujer_9.jpg","cocherocusco@gmail.com","-13.519038430970400","-71.9801665424645","https://www.youtube.com/embed/4BGYioBebuo"),
	(10,"Iñakapalla","Chavez Bermudez",1,"20/06/1985",NULL,"Licenciada en Administración de la Universidad Andina del Cusco en el año 2014, con maestría en Antropología Social de la Universidad Nacional de San Antonio Abad de Cusco (2019). Es una gestora cultural independiente de proyectos de fotografía/ audiovisuales/ artes escénicas/ poesía/ pintura y música. Enlazando los temas de cultura y educación. Escribe poesía desde el año 2000 y sus poemas han sido incluidos en varias antologías a nivel nacional e internacional. Así mismo,es autora de diversos artículos y ensayos académicos de investigación, relacionados a los temas de gestión cultural, economía, educación y emprendimiento social.
Durante los años 2018- 2019, ha participado del proyecto de producción de audiovisuales del EMPODERARTE, dirigido por Karoline Pelikan, directora creativa de la casa PELIKAN PICTURES. 
También ha asesorando y organizando diversos eventos entre ellos, exposiciones de arte, fotografía, recitales de música con la Escuela de Violín Cusco, presentaciones de teatro dirigida a mujeres en el tema del cuidado del medio ambiente, violencia de género, brechas sociales, sororidad, entre otros. Ha sido ganadora de DAFO 2019- Estímulos económicos de fomento a la cultura y segundo lugar del “Concurso de poesía Taiwan 2010” Organizado por: Oficina Económica y Cultural Taiwan 2010 
","img/Mujer_10.jpg","iakachavezb@gmail.com","-13.537326","-71.903965","https://www.youtube.com/embed/-kjIlLVyXc4"),
	(11,"Liliana","Davila Jurado",3,"02/01/1982",NULL,"Liliana Davila Jurado nació en Huaro el año 1982, estudio la primaria y la secundaria en el colegio particular “Luz Casanova” - Lima, ingreso a la Universidad Nacional de San Antonio Abad del Cusco a la Facultad de Antropología, estudio 2 años y luego se traslado a la Universidad Federico Villareal, donde se graduó como antropóloga el 2006.
Realizo realizó varios cursos en Antropología y fotografía. Además realizó una maestría en Gestión Cultural, Patrimonio y Turismo.
Fue fundadora del museo “Piedras Sagradas” de Huaro, Quispicanchi, Cusco. Recibió la medalla junto a su padre en reconocimiento del museo por la Municipalidad Provincial de Quispicanchi. Participo de otros estudios e investigaciones en Lima. Actualmente viene trabajando en la primera publicación de su Poemario. 
","img/Mujer_11.jpg","lidaju@gmail.com","-13.690468","-71.640091","https://www.youtube.com/embed/Kbecwp_WeyE");

INSERT INTO site_web_publicacion(id,titulo,isbn,categorizacion,fecha,descripcion,mujer_id,link_imagen,titulo_disponible,link_disponible) VALUES
	(1,"Sueño Índigo","9786124751028","Cuentos","2018","Libros que contiene dos historias tiernas, acompañadas de espectaculares ilustraciones que te transportarán junto a los protagonistas.",1,"img/Mujer_1_Libro1.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(2,"Colores",NULL,"Cómic","2020","La autora nos cuenta una pequeña anécdota de su infancia en el jardín de su abuela.",1,"img/Mujer_1_Libro2.jpg","Plataforma Behance","https://www.behance.net/gallery/125265469/COLORS-COMIC-Colores-Comic"),
	(3,"Pasado",NULL,"Cómic","2021","Cómic Ganador del Concurso Internacional de Historieta “La sociedad en tiempos de Pandemia” del Festival Virtual Internacional de las artes “Qosqo T’ikarinampaq 2020” Organizado por la Municipalidad del Cusco.",1,"img/Mujer_1_Libro3.jpg","Plataforma Behance","https://www.behance.net/gallery/124964849/PASADO-por-Adriana-Cule-AKA-Madivera"),
	(4,"Antología Ángeles y Demonios",NULL,"Cuentos","1998","Antología organizada por la Asociación Centro Cultural Cusco.",2,"img/Mujer_2_Libro1.jpg","Esta publicación no esta disponible.",NULL),
	(5,"Poemario Acidulce","200901791","Poemario","2009","Éste es su primer poemario, como el título, un cúmulo de dulces y ácidas experiencias",2,"img/Mujer_2_Libro2.jpg","Sitio Web Ana María Milla","https://anamaria.pro/acidulce/"),
	(6,"Mil Poemas a César Vallejo: Una gesta de amor universal",NULL,"Poemario","2012","Ana María Milla participa en esta antología con su poema en la página 349, esta publicación es una recopilación hecha por Alfred Asís Antología-Recopilación-Escritoras, Escritores-Poetas del Mundo.",2,"img/Mujer_2_Libro3.jpg","Enlace Drive","https://drive.google.com/file/d/1k0S8eXwEdFe0iNi_0PyDisx1lE-LiT0c/view?usp=sharing"),
	(7,"La hija del bosque",NULL,"Poemario","2019","La Hija del Bosque es su segundo poemario, y el primero la colección El Retorno de los paganos, colección de publicaciones sobre el retorno a la naturaleza y el viaje interior que toma de pretexto de los viajes físicos hacia otra comprensión del mundo y del universo.",2,"img/Mujer_2_Libro4.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(8,"Poemic: El atardecer del fin del mundo",NULL,"Cómic","2019","Poemic, es una producción que busca fusionar un poema con el arte del cómic. Con el título El atardecer del Fin del Mundo, es un viaje épico en un mundo en guerra, hacia la esperanza de un mundo mejor. Magistralmente ilustrado por el equipo de Qosqomic, liderado por el artista Fabricio Rivas Mar.",2,"img/Mujer_2_Libro5.jpg","Sitio Web Ana María Milla","https://anamaria.pro/poemic/"),
	(9,"Documentos para la historia eclesiástica de Apurímac. Análisis histórico al documento de la peregrinación de Sebastián Quimichi, siglo XVII","27098680","Artículo de revista","2020","El presente trabajo analiza la peregrinación de Sebastián “Quimichi”, a partir de la documentación que pertenece al archivo histórico del Santuario de Cocharcas, específicamente al documento denominado “Relación de la imagen de Nuestra Señora que está en este pueblo de Cocharca hecha por el licenciado don Pedro Guillén de Mendoza en 20 de julio de 1625 años”.",3,"img/Mujer_3_Libro1.jpg","Revista Riqch’ariy Vol. 1, N° 01, 2020. pp. 147-178","https://www.academia.edu/44910438/REVISTA_RIQCH_ARIY_No_01"),
	(10,"El archivo del Santuario de Cocharcas: historia, catalogación y transcripción paleográfica siglos XVI-XX.","287307","Artículo de revista","2017","El motivo del presente trabajo es la difusión de los fondos documentales del Archivo Histórico del Santuario de Cocharcas, cuya recuperación y organización se inició el 2009 a través del entonces Instituto Nacional de Cultura Cusco (INC), institución que se encontraba restaurando el citado santuario. Con el trabajo efectuado, que fue la Puesta en Valor del archivo, se logró poner al servicio libros de cofradías, fábrica, inventarios, empadronamientos, testamentos y libros sacramentales (entierros, bautizos, matrimonios y confirmaciones), además de libros de inicios del siglo xx como litigación de tierras, peticiones y solicitudes, entre otros, que dan cuenta de la vida social, religiosa y cultural del santuario y la doctrina de Cocharcas, desde finales del siglo XVI hasta inicios del XX.",3,"img/Mujer_3_Libro2.jpg","Revista del Archivo General de la Nación N°32, 2017, págs. 287-307","https://revista.agn.gob.pe/ojs/index.php/ragn/issue/view/1/4"),
	(11,"Espacios de inclusión y exclusión: Etnias, ayllus y cofradías en la conformación de la doctrina eclesiástica de Cocharcas 1570-1614.","9786124544637","Artículo de revista","2013","El presente artículo se enmarca en el difícil proceso de reorganización social y religiosa que las poblaciones indígenas padecieron dentro de la región de Huamanga en la coyuntura finisecular del siglo XVI. Nuestra preocupación por comprender dichas reorganizaciones obedece a un doble interés, primero dar cuenta de la conformación del espacio social de la doctrina de Cocharcas, y segundo realizar un análisis de las relaciones interétnicas y las nociones de inclusión/exclusión a partir de la implantación de la institución de la cofradía, convirtiéndose en el medio de mayor eficacia para canalizar y viabilizar los intereses colonial étnicos locales de poder para así ganarse un espacio dentro de la nueva sociedad colonial que se conformaba.",3,"img/Mujer_3_Libro3.jpg","Cuadernos de Investigación Universitaria, 2013, núm. 01. 01 págs. 45-70","https://www.academia.edu/44912519/CUADERNOS_DE_INVESTIGACI%C3%93N_N_01"),
	(12,"El Santuario de Cocharcas: Construcción, clero secular y participación indígena (1611-1680)",NULL,"Articulo de revista","2013","El presente artículo se enmarca en el difícil proceso de reorganización social y religiosa que las poblaciones indígenas padecieron dentro de la región de Huamanga en la coyuntura finisecular del siglo XVI. Nuestra preocupación por comprender dichas reorganizaciones obedece a un doble interés, primero dar cuenta de la conformación del espacio social de la doctrina de Cocharcas, y segundo realizar un análisis de las relaciones interétnicas y las nociones de inclusión/exclusión a partir de la implementación de la cofradía, convirtiéndose en el medio de mayor eficacia para canalizar y viabilizar los intereses colonial étnicos locales de poder para así ganarse un espacio dentro de la nueva sociedad colonial que se conformaba.",3,"img/Mujer_3_Libro4.jpg","Arquitextual N°02, Huancayo, Diciembre 2013, pp 82-102.","https://issuu.com/gusstockconchaflores/docs/arquitextual_2"),
	(13,"Investigación histórica del Santuario de Cocharcas y el Archivo Arzobispal de Abancay.",NULL,"Artículo de revista","2014",NULL,3,"img/Mujer_3_Libro5.jpg","Red de Archivos y Bibliotecas Históricas del Perú","http://archivosybibliotecasdelperu.blogspot.com/2014/03/investigacion-historica-del-santuario_1784.html"),
	(14,"RIQCH´ARIY",NULL,"Edición","2006, 2008, 2020, 2021","Revista de corte social con carácter multidisciplinario producido por el círculo de estudios del mismo nombre pertenecientes a la Facultad de Ciencias Sociales de la Universidad Nacional de San Antonio Abad del Cusco (UNSAAC).",3,"img/Mujer_3_Libro6.jpg","Revista Riqch’ariy ","https://revistariqchariy.com/"),
	(15,"CUADERNOS DE INVESTIGACIÓN UNIVERSITARIA",NULL,"Edición","2012, 2013, 2014","Revista exclusivo para jóvenes y egresados de las diversas carreras profesionales, con el objetivo de dar a conocer los resultados de las investigaciones científicas y los procesos de transferencia tecnológica que se da en la Universidad de San Antonio Abad del Cusco (UNSAAC)",3,"img/Mujer_3_Libro7.jpg","Vicerrectorado de Investigación de la Universidad de San Antonio Abad del Cusco (UNSAAC)","http://vrin.unsaac.edu.pe/"),
	(16,"II SEMANA DE INVESTIGACIÓN",NULL,"Edición","2014","Publicación que conjuga un conjunto de actividades de capacitación y promoción de la investigación científica con el objetivo de generar un espacio plural de debate en relación a la invención, innovación e investigación científica, tecnológica y humanista en la región Cusco con participación de expertos, profesores y estudiantes universitarios de la UNSAAC y el país.",3,"img/Mujer_3_Libro8.jpg","Vicerrectorado de Investigación de la Universidad de San Antonio Abad del Cusco (UNSAAC)","http://vrin.unsaac.edu.pe/"),
	(17,"VADEMÉCUM",NULL,"Edición","2013-2014","El Vicerrectorado de Investigación de la Universidad Nacional de San Antonio Abad del Cusco presenta la publicación VADEMÉCUM DE INVESTIGACIÓN FEDU 2013-2014, que da continuidad a la difusión de las diferentes investigaciones realizadas por grupos de docentes activos y jubilados durante el bienio señalado, los mismos fueron financiados con el Fondo Especial de Desarrollo Universitario (FEDU)",3,"img/Mujer_3_Libro9.jpg","Vicerrectorado de Investigación UNSAAC-VADEMÉCUM - Recursos Digitales","http://vrin.unsaac.edu.pe/publicaciones/1/vademecum-fedu-20132014.html"),
	(18,"Antología Poética del Cusco",NULL,"Poemario","2007","Gladys Conde es acreedora de mención honrosa en poesía por el Premio Regional de Cultura de Cusco (2006), publicándose sus poemas en “Antología Poética del Cusco” realizado por el INC en el 2007.",4,"img/Mujer_4_Libro1.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(19,"Juego y silencio","9786124544811","Poemario","2009","Poemario de 26 poemas cortos, algunos lúdicos otros más serios; donde la poeta relaciona el proceso de creer con metaforas de la naturaleza, el juego y el silencio.",4,"img/Mujer_4_Libro2.jpg","Esta publicación no esta disponible.",NULL),
	(20,"Lliqlla: El canto de la abuela","9786123169701","Cancionero","2020","Gladys Conde ha bebido de la fuente de nuestros ancestros para crear estas maravillosas canciones para el arrullo y el sueño; para crecer y sanar. Los once cantos que incluye este libro nos hacen contemplar la armonía cósmica que reina entre plantas y animales; entre el cielo y la tierra. Las canciones además vienen acompañadas de las luminosas pinturas de la artista plástica Natalya Lizárraga.
",4,"img/Mujer_4_Libro3.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(21,"Cancionero para bebés 2. Colección Tuctupillín","9786124456237","Cancionero","2020","Gladys Conde es parte de este proyecto con 3 canciones. El programa Bebetecas de la Casa de la Literatura Peruana presenta el segundo volumen de Cancionero para bebés. Esta antología reúne más de 30 arrullos, juegos de palabras y canciones que involucran el cuerpo para propiciar el primer vínculo musical de los bebés con el lenguaje. 

",4,"img/Mujer_4_Libro4.jpg","La Casa de la Literatura Peruana","http://www.casadelaliteratura.gob.pe/segundo-cancionero-del-programa-bebetecas/"),
	(22,"Cuentos Aguarunas","DL 2011 00716","Cuentos","2010","Los dos mitos publicados en este folleto han sido tomados del libro Mitos e historias aguarunas de José Luis Jordana Laguna (Retablo de papel ediciones. Lima. 1974); esta publicación trabajada por Guaman Poma de Ayala trae a la vida estos hermosos mitos mediante la ilustración de Natalya Lizarraga.",5,"img/Mujer_5_Libro1.jpg","Plataforma Yumpu","https://www.yumpu.com/es/document/read/14596588/cuentos-aguarunas-en-espanol-guaman-poma-de-ayala"),
	(23,"Identidad, tradición oral y cosmovisión basada en el ecosistema en Perú: reflexiones estéticas desde el surrealismo",NULL,"Artículo de revista","2022","En el presente artículo la ilustradora explica: Lejos de proponer una visión romanizada de la tradición oral y la cosmovisión ancestral, pretendo brindar reflexiones desde mi práctica artística personal y desde la corriente estética del surrealismo sobre los elementos claves de la identidad y los ecosistemas en el Perú. Mucha de la influencia e inspiración nace tanto de artistas y artesanos locales como internacionales. Me enfoco en corrientes que nacieron en la colonia, como es la reconocida Escuela Cusqueña, que tiene como representantes a pintores como Diego Quispe Tito, o el pintor Italiano Bernardo Bitti. Cabe resaltar que los trabajos de la Escuela Cusqueña en mayoría son obras de pintores originarios y mestizos. Obras sacras como las del Corpus Christi siglo XVII de autor anónimo o la obra Virgen del Carmen del siglo XVII, que por su composición se asocia a la representación de la Pachamama, son importantes como antecedente de la pintura actual peruana enfocada en lo tradicional y la ecología",5,"img/Mujer_5_Libro2.jpg","Revista de Ecología Política","https://www.grassrootsjpe.org/publications/visual-essay/identidad-tradicion-oral-y-cosmovision-basada-en-el-ecosistema-en-peru-reflexiones-esteticas-desde-el-surrealismo/?fbclid=IwAR2bXxfO7MwyYIIsEXr961FJz4A8cCgEhcZPoPRSHNzykUUBurOd9u-Okzw"),
	(24,"Lliqlla: El canto de la abuela","9786123270254","Cancionero","2020","Natalya Lizarraga apoya con sus hermosas ilustraciones a Gladys Conde en este cancionero para niños, los once cantos nos hacen contemplar la armonía cósmica que reina entre plantas y animales; entre el cielo y la tierra.",5,"img/Mujer_5_Libro3.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(25,"Usos del quechua en Layo, K´ana suyupi, Cusco","9789995415914","Libro de investigación","2014","Este libro explora la situación sociolingüística del uso del quechua en la comunidad de Taypitunga, Layo, Cusco. Los datos fueron recopilados a través del método etnográfico. Este método posibilitó conocer la versión directa de los hablantes, y en su propio contexto, acerca del proceso actual que el quechua presenta. Las entrevistas y las observaciones de las interacciones de uso del quechua contaron con la participación de jóvenes colegiales y por extensión a los hablantes de la comunidad en general. Los ámbitos que se tomaron como referencia fueron: el hogar, el colegio y la comunidad",6,"img/Mujer_6_Libro1.jpg","DocPlayer","https://docplayer.es/90780283-Usos-del-quechua-en-layo-k-ana-suyupi-cusco.html"),
	(26,"Oro hate emändoya Wachiperi : Diccionario Wachiperi Castellano / DDC-Cusco","9786124686528","Corrección de estilo","2014","(Antonieta realiza la corrección de estilo) El Ministerio de Cultura presentó el Diccionario Wachiperi: Oro Hate Emändoya. La lengua wachiperi, hablada en la provincia de Paucartambo, es una variedad del harakbut. Este diccionario recoge la sabiduría, los conocimientos y expresiones propias de la cosmovisión amazónica de las comunidades nativas de Santa Rosa de Huacaria y Queros Wachiperi; y adquiere una singular importancia para los wachiperi del siglo XXI, interesados en revertir el proceso de debilitamiento en que se encuentra su pueblo ante la disminución de la práctica de su lengua.",6,"img/Mujer_6_Libro6.jpg","Biblioteca Central DDC-Cusco","http://biblioteca.culturacusco.gob.pe/cgi-bin/koha/opac-detail.pl?biblionumber=3948"),
	(27,"Poesía (Quechua y Castellano). Antología de Ganadores de la Categoría “C” : Premio Regional de Cultura, 2015 / Dirección Desconcentrada de Cultura Cusco","DL 201603534","Corrección de estilo","2015","(Antonieta realiza la corrección de estilo en quechua ). Antología de poemas en quechua y castellano de los ganadores de la Categoría “C”. Entre los poetas de esta antología tenemos: Gladis Naty Valencia Rosell, Huchuy harawikunata; Rocío Cjuiro Mescco, Qaqarumicha. Poesía en castellano: Pável Ugarte Céspedes, Repatriación de las aves; Elvis David Quispe Altamirano, Visitame siempre en octubre; Martin Castillo Collado, Primera Dosis; Jhon Hansel Choque Condori, La Palabra no hace el amor, sino la ausencia",6,"img/Mujer_6_Libro5.jpg","Biblioteca Central DDC-Cusco","http://biblioteca.culturacusco.gob.pe/cgi-bin/koha/opac-detail.pl?biblionumber=8894"),
	(28,"Quechua, idioma que puede hacer retornar la vida de comunidad: Runasimiqa ayllumanmi kutichinman","9789568416461","Ensayo","2016","Este ensayo trata sobre la inserción tímida de este proceso reivindicativo y justiciero en el contexto y escenario histórico, simbólico, práctico, institucional, familiar, personal",6,"img/Mujer_6_Libro2.jpg","Ariadnaediciones","https://ariadnaediciones.cl/index.php?option=com_content&view=article&layout=edit&id=153"),
	(29,"Poesía Súper Contemporánea de Perú y Estados Unidos.","9789569853104","Traducción","2017","(Antonieta participa en el grupo de traductores de esta obra) Poesía súper contemporánea de Perú y Estados Unidos es un libro sensual y necesario. Entre sus páginas se encuentran las voces más destacadas del movimiento literario alt-lit de Estados Unidos con una intensa muestra de poesía peruana contemporánea: individual y colectiva, del campo y la ciudad, tradicional y de vanguardia al mismo tiempo.",6,"img/Mujer_6_Libro7.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(30,"Revista Saqsaywaman N°10",NULL,"Corrección de estilo","2018","(Antonieta realiza la corrección de estilo en quechua ) Nuevos aportes a la Arqueología del Periodo Formativo del Cusco en Marcavalle, Minaspata y Kullupata.",6,"img/Mujer_6_Libro4.jpg","Esta publicación no está disponible.",NULL),
	(31,"Balance preliminar en torno a avances, desafíos y oportunidades de la consulta previa en el Perú","9786124740831","Ensayo","2018","El trabajo de investigación ofrece una mirada panorámica de la consulta previa en cinco apartados. Los procesos vinculados a la consulta previa vislumbran el punto de quiebre que dio origen a los diferentes eventos, etapas, acuerdos y desacuerdos que sirvieron de preámbulo a la promulgación de la ley y su reglamento.",6,"img/Mujer_6_Libro3.jpg","Centro de Estudios Constitucionales (CEC) Colección  “Derecho y Sociedad” 2017","https://www.tc.gob.pe/wp-content/uploads/2018/10/Justicia-e-interculturalidad.pdf"),
	(32,"5to Festival Caravana de Poesía Cusco - Ayacucho","9786124770265","Poemario","2018","Antología de poemas en castellano y quechua.",6,"img/Mujer_6_Libro8.jpg","Esta publicación no está disponible.",NULL),
	(33,"Relato Puriy kutiy (El viaje del retorno)",NULL,"Cuento","2012","La autora nos comenta que este relato fue publicado en Noqanchis No. 5. revista bilingüe quechua-asháninka, 2012",6,"img/Mujer_6_Libro9.jpg","Esta publicación no está disponible.",NULL),
	(34,"Rojo","9786124788512","Novela","2018","En el año 1932, Matilde tiene 15 años y tras la muerte de su padre, es ofrecida en casamiento a Artemio Urbina, hombre adinerado que dedica su vida a viajes y fiestas. Rojo es la historia del mundo interior de Matilde, pero también de su encuentro con el diario de Lavinia Vigorou, primera esposa de Artemio e importante pianista de la época cuyos escritos revelan libertad y cultos esotéricos, fragmentos íntimos que abren las puertas a un paisaje sensorial y espiritual, que cogen la mano de la protagonista para intentar salvarla del vacío.",7,"img/Mujer_7_Libro1.jpg","Editorial Forjadestino","https://www.facebook.com/forjadestino/"),
	(35,"De los vientos o la muerte","9786124788574","Novela","2021","Mercedes tenía dieciséis años cuando un hombre vestido con un terno blanco fue a recogerla para llevarla por primera vez a la Amazonía. Al pasar los treinta, siente que jamás podrá acostumbrarse a vivir en aquel lodazal olvidado del mundo. Busca aferrarse a algo, a alguien, pero está sola. Rodeada de un interminable abismo.",7,"img/Mujer_7_Libro2.jpg","Editorial Forjadestino","https://www.facebook.com/forjadestino/"),
	(36,"Un trozo desprendido de la luna",NULL,"Relato","2021","Lucy Fernandez traza desde los hábitos y costumbres de Tomasa Amat y García Mancebo dama de la sociedad involucrada en la causa independentista y nieta de famosa Perricholi, el recorrido de San Martín desde su desembarcación en Paracas hasta la proclama de la independencia en Lima. (Parte de 21. Relatos sobre mujeres que lucharon por la Independencia del Perú)",7,"img/Mujer_7_Libro3.jpg","Petro Perú Gestión Cultural","https://cultura.petroperu.com.pe/biblioteca-cope/veintiun-relatos-volumen-dos/"),
	(37,"La cocina",NULL,"Relato Erótico","2016","Lucy Fernandez participa en la Antología de microrrelatos eróticos II titulado “69”, trabajo seleccionado por Carolina Cisneros para editorial Altázor. Una cuidadosa edición en formato pequeño que reúne a 69 escritoras que presentan 69 microrrelatos, en tono erótico, con la peculiaridad de estar escritos en 69 palabras.",7,"img/Mujer_7_Libro4.jpg","Esta publicación no está disponible.",NULL),
	(38,"La flor en que amaneces. Edición V.","DL ZU2021000284","Antología","2021","Lenyan Veka participa en esta antologia poetica de Serie Asteroide (Venezuela) con sus poemas: “Figura en Verso”, “Amanece”, “Sobre el cuerpo”.",8,"img/Mujer_8_Libro1.jpg","Issuu","https://issuu.com/edicionesazalea/docs/la_flor_en_que_amaneces_-_n_mero_cinco"),
	(39,"Voces de la poesía peruana","9786124868603","Antología","2021","Lenyan Veka participa en esta antologia poetica realizada por Helard Fuentes. Es una obra que reúne la muestra poética de destacados escritores a nivel nacional, así como aquellas voces emergentes en la contemporaneidad, planteando un sentido integrador propuesto por su autor en base a cuatro criterios: intercultural, interregional, interdisciplinario e intergeneracional.",8,"img/Mujer_8_Libro2.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(40,"En octubre si hay milagros, Antología Poética",NULL,"Antología","2021","Lenyan Veka participa en esta antologia poetica de la editorial Z3ntauro",8,"img/Mujer_8_Libro3.jpg","Esta publicación no está disponible.",NULL),
	(41,"Tu voz existe, Antología Poética",NULL,"Antología","2020","Lenyan Veka participa en esta antologia poetica realizada por Colectivo Femenino Cultural Atenea. Siendo este un homenaje a Adela Montesinos.",8,"img/Mujer_8_Libro4.jpg","Colectivo Femenino Cultural Atenea","https://www.facebook.com/Colectivo-Femenino-Cultural-Atenea-108899337148451/"),
	(42,"Tu voz existe, Antología Poética",NULL,"Antología","2019","Lenyan Veka participa en esta antologia poetica realizada por Colectivo Femenino Cultural Atenea. Siendo este un homenaje a Carmela Nuñez Ureta.",8,"img/Mujer_8_Libro5.jpg","Colectivo Femenino Cultural Atenea","https://www.facebook.com/Colectivo-Femenino-Cultural-Atenea-108899337148451/"),
	(43,"Revista Watanay. Edición abril 2021. (Cusco).",NULL,"Revista","2021","Lenyan Veka tiene su participación en esta revista Watanay, bastion de la kultura Kuzko, ABRIL de 2021 BRIL de 2021
Kuzqo - Perú año 4 - número 8 4to. temporal (edixión modorra).",8,"img/Mujer_8_Libro6.jpg","Enlace Drive","https://drive.google.com/drive/folders/1L-XBXdF5Qjz-5ROkk2v4VomnMhY82ANs"),
	(44,"Aislados·Dosis de poesía para tiempos inciertos","9786124799228","Antologia","2020","Lenyan Veka participa en esta antologia poetica. En un año ciertamente inesperado y difícil, nos hemos dado a la tarea de salvar las distancias y unirnos más a través del verbo hecho arte: la poesía. Fruto de ese esfuerzo y hermandad es esta primera dosis digital que reúne a 89 voces contemporáneas de diversas nacionalidades, quienes no han dejado ni dejarán de forjar la palabra a pesar de los tiempos adversos.",8,"img/Mujer_8_Libro7.jpg","Dendro Casa Editorial Independiente","https://dendroeditorial.wordpress.com/2020/08/20/aislados-dosis-de-poesia-para-tiempos-inciertos/"),
	(45,"Crudo, revista de poesía e ilustración # 2. Editorial",NULL,"Revista","2020","Es una publicación de Loko El Gato la Editorial/Difusora. Con la participación de los ilustradores Favio Carranza y Chontano Gamarra de Bolivia. Participan con poesía: Cesar Hidalgo (Chile), Jose Villanueva (Bolivia), Lenyan Veka (Perú), Inti Villasante (Bolivia), Pep Balcárcel (Guatemala), Shantra Mantra (Bolivia), Pavel Ugarte (Perú), Ana Medinacelli (Bolivia), Toño Niño (Colombia). Crudo #2 desde Bolivia para el mundo.",8,"img/Mujer_8_Libro8.jpg","Loko: El gato","https://www.facebook.com/LokoElGato"),
	(46,"El color de las palabras",NULL,"Antología","2019","Lenyan Veka participa en esta antologia poetica. Antología de Colección Festival Internacional de Poesía Joven Jauría Palabras 2019 (Santa Cruz, Bolivia).",8,"img/Mujer_8_Libro9.jpg","Esta publicación no está disponible.",NULL),
	(47,"5to Festival Caravana de Poesía Cusco - Ayacucho.","9786124770265","Antologia","2018","Lenyan Veka participa en esta antologia poetica. Antología de poemas en castellano y quechua.",8,"img/Mujer_8_Libro10.jpg","Esta publicación no está disponible.",NULL),
	(48,"Mixtura de poesía en el ensarte de las artes.",NULL,"Antologia","2018","Lenyan Veka participa en esta antologia poetica.Mixtura de poesía en el ensarte de las artes es una edición conmemorativa de los 25 años del Festival del Arco iris, Cusco.",8,"img/Mujer_8_Libro11.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(49,"Enero en la Palabra XVIII Festival de poesía del sur andino.",NULL,"Antologia","2014","Lenyan Veka participa en esta antologia poetica. “Enero en la Palabra”, gran encuentro de poetas realizado cada año en enero, con la participación poetas cusqueños, nacionales e internacionales, con el apoyo de la Dirección Desconcentrada de Cultura Cusco.",8,"img/Mujer_8_Libro12.jpg","Esta publicación no está disponible.",NULL),
	(50,"Enero en la Palabra XIX Festival de poesía del sur andino, En el hemisferio femenino.",NULL,"Antologia","2015","Lenyan Veka participa en esta antologia poetica. “Enero en la Palabra” gran encuentro de poetas realizado cada año en enero, con la participación poetas cusqueños, nacionales e internacionales, con el apoyo de la Dirección Desconcentrada de Cultura Cusco. Enero en la palabra XIX, tiene dos prioridades visualizar el trabajo de óetas mujeres y ña poesia en lenguas originarias.",8,"img/Mujer_8_Libro13.jpg","Esta publicación no está disponible.",NULL),
	(51,"Enero en la Palabra XXII Festival de poesía del sur andino.",NULL,"Antologia","2018","Lenyan Veka participa en esta antologia poetica. “Enero en la Palabra XXII”, gran encuentro de poetas realizado cada año en enero, con la participación poetas cusqueños, nacionales e internacionales, con el apoyo de la Dirección Desconcentrada de Cultura Cusco.",8,"img/Mujer_8_Libro14.jpg","Esta publicación no está disponible.",NULL),
	(52,"7to Festival Caravana de Poesía Pisco-Lima-Huancayo",NULL,"Antologia","2022","Lenyan Veka participa en esta antologia poetica. Antología de poemas en castellano y quechua.",8,"img/Mujer_8_Libro15.jpg","Esta publicación no está disponible.",NULL),
	(53,"Narradores cusqueños : Estudio Preliminar, antología y notas",NULL,"Antología","1984","El cuento de Emperatriz Escalante, “La bruja buena” fue incluido en la Antología de Narradores Cusqueños de Rubén Sueldo Guevara (1984)",9,"img/Mujer_9_Libro1.jpg","Biblioteca Central DDC-Cusco","http://biblioteca.culturacusco.gob.pe/cgi-bin/koha/opac-detail.pl?biblionumber=567"),
	(54,"II Juegos Florales Magisteriales de la Región Inka",NULL,"Antologia","1990","Emperatriz Escalante participa en esta antologia con su cuento “Los pastorcitos”, con el cual obtiene el 2do lugar.",9,"img/Mujer_9_Libro2.jpg","Esta publicación no está disponible.",NULL),
	(55,"El nuevo Pinocho",NULL,"Cuentos","2005","En este breve libro hay 5 cuentos:El Nuevo Pinocho, El Trovador, La Bruja Buena, Los Vampiros, El Curandero.",9,"img/Mujer_9_Libro3.jpg","Esta publicación no está disponible.",NULL),
	(56,"Antologia de Cuentos en Quechua",NULL,"Antologia","2006","Emperatriz Escalante obtuvo mención honrosa en el Premio Regional de Cultura del INC, siendo publicado en esta antología.",9,"img/Mujer_9_Libro4.jpg","Esta publicación no está disponible.",NULL),
	(57,"MIS LECTURAS PREFERIDAS I – Obra en dos idiomas. (3er grado)","9786124654992","Antología","2016","Algunos escritos de Emperatriz Escalante aparecen en esta selección de cuentos, narraciones, mitos y leyendas, para lectores de 3er grado de primaria. Obra que crea hábitos de lectura y despierta el interés en los niños por los libros. Inculcan valores como la honradez, disciplina, el orden, la solidaridad, el desprendimiento, el compromiso, el respeto, etc.",9,"img/Mujer_9_Libro5.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(58,"MIS LECTURAS PREFERIDAS II – Obra en dos idiomas. (4to grado)","9786124732706","Antología","2016","Algunos escritos de Emperatriz Escalante aparecen en esta selección de cuentos, narraciones, mitos y leyendas, escogidos para lectores de 4to grado; obra que ayuda a crear hábitos de lectura e interés por los libros. Inculcan valores como la honradez, la estima, la disciplina, el orden, la solidaridad, el desprendimiento, el compromiso, el respeto, etc. Contiene, además, interculturalidad, inclusión social, identidad regional y nacional, costumbres, tradiciones y orgullo por lo nuestro.",9,"img/Mujer_9_Libro6.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(59,"MIS LECTURAS PREFERIDAS I – Obra en dos idiomas. (5to grado)","9786124732713","Antología","2016","Algunos escritos de Emperatriz Escalante aparecen en este volumen que compila una selección de temas entre cuentos, narraciones, mitos y leyendas para lectores del 5to grado de primaria; es una obra que promueve y crea hábitos de lectura, consolida el interés por los libros, refuerza la capacidad de analizar y comprender de mejor manera lo leído. Son lecturas que inculcan los distintos valores humanos dentro de los conceptos de interculturalidad e inclusión social. Es una obra que rescata identidad regional y nacional, revalora las costumbres, tradiciones y genera orgullo por lo nuestro.",9,"img/Mujer_9_Libro7.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(60,"Los vampiros","9786125001115","Cuento","2020","Una familia de las zonas alto andinas y apremiada por las necesidades, decide trasladarse y vivir en un pequeño lugar ubicado en plena ceja de selva; sin embargo, las raras muertes de sus animales, la falta de apoyo médico oportuno, el riesgo de sus propias vidas, harán que decidan afrontar directamente al causante de tantas muertes y el que tendrá un final sorprendente.
Esta lectura enseña lo importante de evaluar y hallar soluciones para luego tener el valor de ejecutarlas.",9,"img/Mujer_9_Libro8.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(61,"El libro = Qelqasqa patara","9786125001061","Cuento","2020","Un joven apasionado de los libros, descubre un ejemplar al cual no puede acceder; impulsado por su deseo de poder leerlo, de tener en sus manos y deleitarse con la lectura de dicha obra, lo hará cometer un grave error. Los resultados de su proceder, no se dejan esperar, y son acontecimientos lamentables. Esta narración, enseña a más de valores, a ser perseverante, pero también, paciente, y ante las circunstancias adversas, a ser prudente.",9,"img/Mujer_9_Libro9.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(62,"Suyaypaq Takin","9786124392290","Cuento","2020","El libro Suyaypaq Takin. Cuentos y poemas en quechua responde a ambas necesidades. Incluye dos cuentos finalistas en concursos regionales, que fueron publicados por las respectivas instituciones organizadoras de esos certámenes. Esta edición reúne estos y otros cuentos de la autora, constituyendo un cuerpo de relatos bilingües, que describen los valores, dificultades y retos de los pueblos andinos contemporáneos, expresando la belleza y potencia de esta milenaria cultura. También trae nueve poemas de la autora, todos en runasimi (quechua), que muy bien pueden acompañar actividades escolares por su temática regional, histórica, vivencial y reflexiva.",9,"img/Mujer_9_Libro10.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(63,"Tatiana","9786125001139","Cuento","2020","Este cuento relata el drama de una jovencita que se siente equivocadamente marginada, postergada por cuestiones raciales, su lucha íntima con los traumas y la falta de autoestima. Un tema difícil en círculos donde existen personas con serios complejos de inferioridad y que los convierten en seres que excluyen, critican y cuestionan a los hombres por su color. Esta narración, ayuda al lector a comprender bien que no existe razones válidas para considerar a las personas por su color, como más o menos aptas que las otras, asimismo inculca a ser inclusivos y solidarios.",9,"img/Mujer_9_Libro11.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(64,"Compadricha","9786125001047","Cuento","2020","La soledad de un hombre ya maduro, hace que éste reflexione sobre su vida de un modo sincero y sencillo con su mejor amigo, un perro también ya viejo; recuerda algunos sucesos de su juventud y que permite al lector evaluar la situación social de los campesinos hace años atrás y que de algún modo aún hoy pervive. Enseña la importancia de la reflexión y de aprender de las experiencias vividas.",9,"img/Mujer_9_Libro12.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(65,"El Curandero","97861250001054","Cuento","2020","Una serie de emergencias humanas, enfermedades y muertes por falta de auxilio oportuno, motivaran que una familia decida tomar una actitud y un cambio radical en sus activdades cotidianas, para bien para los pueblos ubicados en la selva.",9,"img/Mujer_9_Libro13.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(66,"Cuadernos incompletos",NULL,"Poemario","1969","Este poemario de Felix Flores Becerra esta acompañado de las ilustraciones de Emperatriz Escalante.",9,"img/Mujer_9_Libro14.jpg","Esta publicación no está disponible.",NULL),
	(67,"Lunas de ébano",NULL,"Poemario","2022","Podemos conceptualizar su trabajo en la expresión de 
la eternidad y de las cosas, seres y fenómenos de la naturaleza, pues aluden a su hija y 
a su madre, al Amazonas, a Cashiri (la luna masculina de los Ashaninka), a Machu Picchu…, que son también elementos propios de nuestro paisaje interior —y también del 
entorno cosmogeoecológico.",10,"img/Mujer_10_Libro1.jpg","Directamente con la autora","https://www.facebook.com/inakapalla.chavezbermudez"),
	(68,"Ellas: tejiendo historias desde el hilo rojo","9796114125181","Libro de investigación","2021","En esta serie de historias de mujeres cusqueñas Ellas, tejiendo historias desde el hilo
rojo, se reflexiona y evidencia el coraje y determinación de las mujeres del pasado al
defender sus ideales de justicia y libertad que abrieron camino a millones de peruanas
para luchar frente a las violencias de género.",10,"img/Mujer_10_Libro2.jpg","Drive","https://drive.google.com/file/d/1ZEHpW5isb-Wl1SlOi4rFeSYfADVj3bK4/view?usp=sharing"),
	(69,"Series de columnas en PULSO REGIONAL",NULL,"Columna","2019-2021","Un conjunto de 17 articulos dentro de la revista PULSO REGIONAL, los tópicos que resaltan son el arte, la litearuta, la investigación entre otros.",10,"img/Mujer_10_Libro3.jpg","PULSO REGIONAL","https://www.pulsoregional.pe/category/inakapalla-chavez/"),
	(70,"Eulogio Nishiyama y su acervo fotográfico del Cusco",NULL,"Articulo de revista","2019","Iñakapalla realiza un articulo en la revista “ Patrimonio N° 17” de marzo del 2019.",10,"img/Mujer_10_Libro4.jpg","Patrimonio en Issuu","https://issuu.com/drccusco/docs/revista_patrimonio_17_ddc-c/24"),
	(71,"La Cultura desde todos los Puntos de Vista: Una propuesta de modelo de desarrollo cultural en Brasil aplicada en Perú 
(Análisis del Libro Ponto de Cultura: O Brasil de baixo para cima- Celio Turino)","2013-10990","Artículo de revista","2013","Pagina 8, Análisis del Libro Ponto de Cultura: O Brasil de baixo para cima- Celio Turino por parte de Iñakapalla Chávez.",10,"img/Mujer_10_Libro5.jpg","Inkari Cultura","https://dokumen.tips/documents/revista-inkari-pdf.html?page=6"),
	(72,"Antologia de Poemas. Flora Tristan",NULL,"Antolgia","2012","Iñakapalla comparte algunos de sus poemas que aparecen en su poemario “Lunas de Añil”",10,"img/Mujer_10_Libro6.jpg","Pagina de Flora Tristan","http://www.flora.org.pe/poesia.htm"),
	(73,"Escenificación de Ceremonia Ancestral Wanakauri: La Política y la cultura van de la mano",NULL,"Columna","2010","Iñakapalla realiza esta columna en el diario: Diario el Sol del Cusco. En junio del 2010.",10,"img/Mujer_10_Libro7.jpg","Esta publicación no está disponible.",NULL),
	(74,"Biografía del fotógrafo cusqueño Eulogio Nishiyama",NULL,"Articulo de revista","2010","Iñakapalla realiza un articulo en la revista virtual “Gaseta Cultural Cusco“. Año 1, diciembre 2011.",10,"img/Mujer_10_Libro8.jpg","Gaseta Cultural Cusco en Issuu","https://issuu.com/art-restauro/docs/gacetaculturalcusco-diciembre2011"),
	(75,"Historia de la Moda cusqueña",NULL,"Columna","2008","Iñakapalla realiza esta columna en el diario: Diario el Sol del Cusco. En setiembre del 2008.",10,"img/Mujer_10_Libro9.jpg","Esta publicación no está disponible.",NULL),
	(76,"Los fotógrafos minuteros en Cusco",NULL,"Columna","2008","Colaboración en reportaje publicado en revista Somos del Diario El Comercio- Lima. Noviembre 2008.",10,"img/Mujer_10_Libro10.jpg","Esta publicación no está disponible.",NULL),
	(77,"Perú s. XXI. 60 poetas peruanos contemporáneos",NULL,"Antología","2007","Iñakapalla participa en esta antología realizada por la Escuela de Lima de Yacana Arte y Rock.",10,"img/Mujer_10_Libro11.jpg","Liberia del Sur","https://www.libreriasur.com.pe/libro/poesia-peru-s-xxi_123010"),
	(78,"La Makina de coser poemas",NULL,"Blog Personal","2007","Revista Online donde Iñakapalla realiza sus analisis de poesia y tambien comprate su creación Poetica, junto con algunos afiches de su autoria.",10,"img/Mujer_10_Libro12.jpg","BlogsPot","http://lamakinadecoserpoemas.blogspot.com/"),
	(79,"Lunas de Añil",NULL,"Poemario","2005","Los temas de su poesía son de manera muy marcada la luna y los sueños, está presente también el tema del amor. Otro tema muy fuerte es la necesidad imperiosa de escribir, necesidad que se presenta con deseo y pasión adictiva. Entre otros temas de su poesía son la soledad, la ciudad silente, en la que el yo poético siempre se dirige hacia el sur, el paso tan apresurado del tiempo y de los días, otro tópico clásico de la poesía.",10,"img/Mujer_10_Libro13.jpg","Esta publicación no está disponible.",NULL),
	(80,"Inti Raymi- Fiesta del Sol- Fundamentación documental del cuadro de Alfredo Rocha Segarra por el Dr. Manuel Chávez Ballón",NULL,"Libro de investigación","2016","En esta publicación es responsable de la investigación Iñakapalla Chávez Bermúdez y Ricardo Ráez Reátegui, en una reedición del trabajo de su abuelo Manuel Jorge Chávez Ballón.
",10,"img/Mujer_10_Libro14.jpg","Drive","https://drive.google.com/file/d/1Lhj2jDNUhCyViwhSuaTnafnE1AVzOueG/view?usp=sharing"),
	(81,"Liliana Davila Jurado",NULL,"Blog Personal","2022","El blog personal de Liliana Davila Jurado, esta constituido por distintos articulos sobre antropologia y algunos versos de la autora.",11,"img/Mujer_11_Libro1.jpg","BlogsPot","http://lidaju.blogspot.com/"),
	(82,"El Wayqui",NULL,"Libro de investigación","2015","El libro relata aspectos del hallazgo de la momia denominada El Wayqui, donde se pretende despertar el interés de los lectores en torno a temas de vida extraterrestre y posibles influencias en algunos aspectos culturales en la tierra. Este libro lo trabaja con su padre Renato Davila Riquelme en coautoria.",11,"img/Mujer_11_Libro2.jpg","Directamente con la autora","https://www.facebook.com/liliana.davilajurado.3"),
	(83,"Piedras Sagradas","DL 11723-2011-05804","Libro de investigación","2011","Publicación realizada por los antropólogos Renato Davila Riquelme y Liliana Davila Jurado, dicho libro muestra el trabajo previo que se realizó para la apertura del actual Museo Piedras Sagradas de Huaro; ubicación, aspectos museográficos, sociales, etc. Así como una interpretación de la iconografía hallada en cada petroglifo que hoy forman parte de Museo de sitio.",11,"img/Mujer_11_Libro3.jpg","Directamente con la autora","https://www.facebook.com/liliana.davilajurado.4");

INSERT INTO site_web_ejerce(id,mujer_id,categoria) VALUES
	(1,1,"Il"),
	(2,1,"Es"),
	(3,1,"Co"),
	(4,2,"Po"),
	(5,2,"Es"),
	(6,3,"Hi"),
	(7,3,"Ed"),
	(8,4,"Po"),
	(9,5,"Il"),
	(10,6,"Es"),
	(11,6,"Ed"),
	(12,6,"Cr"),
	(13,6,"Tr"),
	(14,7,"Es"),
	(15,8,"Po"),
	(16,9,"Es"),
	(17,9,"Il"),
	(18,10,"Po"),
	(19,10,"Es"),
	(20,10,"Cl"),
	(21,11,"Es"),
	(22,11,"An"),
	(23,11,"Po");

INSERT INTO site_web_evento(id,titulo,descripcion,link_imagen,nombre_organizador,logo_organizador,fecha_publicacion,link_organizador,fecha_evento,link_facebook) VALUES
	(1,"26° FERIA INTERNACIONAL DEL LIBRO DE LIMA","Prepárate para disfrutar de esta gran fiesta de los libros. ¡Comparte con los tuyos la Experiencia FIL!","img/eventosAndDescuentos/evento-6.jpg","Cámara Peruana del Libro","img/eventosAndDescuentos/cpl.jpg","2022-05-09","https://cpl.org.pe/",null,"https://www.facebook.com/FilLimaPeru/posts/2512333538904033/"),
	(2,"FERIA INTERNACIONAL DEL LIBRO DE IQUITOS",'Esta primera edición de la "FILI" (Feria Internacional del Libro de Iquitos) tiene el placer de dar a conocer a algunos de los escritores y críticos literarios que nos acompañarán del 15 al 22 de mayo.',"img/eventosAndDescuentos/evento-7.jpg","Filiquitos","img/eventosAndDescuentos/fili.jpg","2022-05-09","https://www.filiquitos.pe/",null,"https://www.facebook.com/Filiquitos/photos/101298799255271/"),
	(3,"VII FESTILIBRO 2022 AREQUIPA","Te invitamos a participar del VII FESTILIBRO en Arequipa una feria donde encontrarás muchas sorpresas: recitales, conservatorios, cuenta cuentos, actividades culturales, libros escolares, entre otros.","img/eventosAndDescuentos/evento-8.jpg","Municipalidad Provincial de Arequipa","img/eventosAndDescuentos/mun_are.jpg","2022-05-13","https://www.muniarequipa.gob.pe/",null,"https://www.facebook.com/entrelineascultu/posts/1573327529734544/"),
	(4,'REVISTA "LIBROS Y MÁS"','Ya está disponible la 3era edición de la revista "Libros y más". En ella encontrarás muchas noticias sobre nuestras tiendas y de las campañas que tenemos para ustedes. Además, conoce más sobre la escritora, editora y antropóloga peruana Karina Pacheco Medrano',"img/eventosAndDescuentos/evento-9.jpg","Librerías Crisol","img/eventosAndDescuentos/crisol.jpg","2022-05-14","https://www.crisol.com.pe/",null,"https://www.facebook.com/libreriascrisol.paginaoficial/photos/a.120619034635612/5446204215410374/"),
	(5,"SEMANA DE LA EDUCACIÓN ARTÍSTICA","Súmate a esta jornada de arte y educación para abordar temas del contexto actual de la educación artística en la escuela y participa de los talleres presenciales y virtuales para afianzar tus capacidades y habilidades pedagógicas.","img/eventosAndDescuentos/evento-10.jpg","Ministerio de Cultura del Perú","img/eventosAndDescuentos/mdc.jpg","2022-05-17","https://www.gob.pe/cultura/",null,"https://www.facebook.com/mincu.pe/posts/337686675117055/"),
	(6,"30% DE DESCUENTO EN CRECIMIENTO PERSONAL","Hasta el 28 de mayo tendremos hasta 30% de descuento en miles de libros.","img/eventosAndDescuentos/evento-11.jpg","Librería Buen Salvaje","img/eventosAndDescuentos/buensalvaje.jpg","2022-05-18","https://www.buensalvaje.com/",null,"https://www.facebook.com/buensalvajecom/posts/5235544399861015/"),
	(7,"VOCES EN LENGUAS ORIGINARIAS: TRES POETAS PERUANAS CONTEMPORÁNEAS","Conozcamos a tres poetas contemporáneas en la jornada Voces en lenguas originarias. Participa este jueves 26, a las 6 p.m.","img/eventosAndDescuentos/evento-12.jpg","Casa de la Literatura Peruana","img/eventosAndDescuentos/clp.jpg","2022-05-19","https://www.casadelaliteratura.gob.pe/",null,"https://www.facebook.com/CasaLiteratura/posts/5227050394021150/"),
	(8,"BOLETÍN MENSUAL DE OPORTUNIDADES FORMATIVAS PARA ARTISTAS Y TRABAJADORES DEL ARTE","El Ministerio de Cultura lanza el primer Boletín de Oportunidades de Formativas - edición mayo 2022, el cual contiene información sobre las actividades mensuales que su servicio Conecta viene organizando.","img/eventosAndDescuentos/evento-13.jpg","Ministerio de Cultura del Perú","img/eventosAndDescuentos/mdc.jpg","2022-05-20","https://www.gob.pe/cultura/",null,"https://www.facebook.com/mincu.pe/posts/337686675117055/"),
	(9,"REPENSAR LAS POLÍTICAS PARA LA CREATIVIDAD","¿Cómo reconstruir mejor el sector cultural? No te pierdas la presentación nacional del nuevo informe de la UNESCO Perú.","img/eventosAndDescuentos/evento-14.jpg","Ministerio de Cultura del Perú","img/eventosAndDescuentos/mdc.jpg","2022-05-20","https://www.cusco.gob.pe/bmc/",null,"https://www.facebook.com/buensalvajecom/posts/5235544399861015/"),
	(10,"DESCUBRE LAS NOVEDADES DE LIBRERÍA SBS","¿Ya viste todas las novedades que tenemos para ti? ¡Encuentra ya tu próxima lectura!","img/eventosAndDescuentos/evento-15.jpg","Librería SBS Perú","img/eventosAndDescuentos/sbs.jpg","2022-05-21","https://www.sbs.com.pe/",null,"https://www.facebook.com/libreriasbs/posts/5234550009924258/");