DELETE FROM site_web_lugar;
DELETE FROM site_web_mujer;
DELETE FROM site_web_publicacion;
DELETE FROM site_web_ejerce;

INSERT INTO site_web_lugar(id,region,provincia,distrito) VALUES
	(1,"Cusco","Cusco","Cusco"),
	(2,"Cusco","Canas","Layo"),
	(3,"Cusco","Quispicanchi","Huaro"),
	(4,"Cusco","Acomayo","Acomayo");

INSERT INTO site_web_mujer(id,nombre,apellido,lugar_id,fecha_nacimiento,fecha_defuncion,trayectoria,link_imagen,Contacto,coordx,coordy,Entrevista) VALUES
	(1,"Adriana Hiromi ","Cule Vargas",1,"20/04/1996",NULL,"Adriana Cule es una artista visual y retratista profesional. Se desenvuelve en el terreno del diseño gráfico, el modelado análogo y digital, el desarrollo de personajes pintorescos y la creación de cuentos cortos. En sus obras busca que las perspectivas y composición interactúen con el espectador exagerando las formas.
Ha participado en diferentes proyectos, muestras artísticas, diferentes campañas y producciones entre ellas la inauguración de Saga Falabella en Cusco, la filmación de Transformers en Cusco y la iniciativa de “Hagamos un Perú que de gusto” de Inca Kola.
Ilustro el cuento “El zorro y el cóndor” de Maximo Ccama, realizo el libro de cuentos “Sueño Índigo” y los cómics “Pasado” y “Colores”.","img/Mujer_1.jpg","yozoh2004@gmail.com
","-13.518936101916335 ","-71.98050471302038","https://www.youtube.com/embed/Nz-d6tKw4wA"),
	(2,"Ana Maria","Milla Hurtado",1,"15/06/1977",NULL,"Cusqueña de nacimiento, administradora de formación. Desde el 2003 ha participado como gestora cultural como productora de eventos y posteriormente la primera agenda cultural virtual, Agenda Cusco. Tiene trayectoria de empresaria turística del 2002, como diseñadora y productora de eventos durante 9 años. Ha participado en numerosos recitales, como poeta y productora. Actualmente dirige el Planetarium Cusco, centro de interpretación cultural, planetario y observatorio, lugar donde se difunde la ciencia, el universo y la astronomía cultural de los inkas. Es también feliz de mamá de tres y artista floral","img/Mujer_2.jpg","anamaria@planetariumcusco.com","-13.5219062351864","-71.95797387209109","https://www.youtube.com/embed/KezcLgAdhTA"),
	(3,"Angela María"," Concha Pacheco",1,"06/06/1980",NULL,"Angela M. Concha es licenciada en Historia por la Universidad Nacional de San Antonio Abad del Cusco. Magister en Historia de América Latina, Mundos Indígenas por la Universidad Pablo de Olavide en Sevilla-España, y candidata a Doctora en Historia y Estudios Humanísticos: Europa, América, Arte y Lenguas por la misma Universidad. Con experiencia en trabajos sobre patrimonio documental y monumental (templos, casonas coloniales, centros arqueológicos y archivos históricos), en labores de conservación, catalogación e investigación. Docente de la Universidad de Salamanca (España)/ International Studies Abroad (ISA-Cusco) y de la Universidad Nacional de San Antonio Abad del Cusco. 
","img/Mujer_3.jpg","angelamaria11y6@gmail.com","-13.5215231640725","-71.95862120997890","https://www.youtube.com/embed/v7WSLHeSR44"),
	(4,"Gladys","Conde Camargo",1,"07/03/1982",NULL,"Poeta y cantautora. Ha sido acompañante musical en centros de educación inicial de Cusco. También facilitadora de talleres en torno del arrullo para madres gestantes, madres adolescentes, abuelos, recien nacidos, profesores, médicos y enfermeros.
Obtuvo una mención honrosa en poesía por el Premio Regional de Cultura de Cusco (2006), publicándose sus poesías “Antología Poética del Cusco” INC (2007), “Juego y silencio” Editorial Saqra (2009), “Lliqlla. El Canto de la abuela” (2020) por el Fondo Editorial SM. Sus composiciones musicales que son poesías hechas canción que se encuentran en los discos ”Zorrito Ramón” (2011), “Intiwawacha” (2012); “El vuelo de katari” (2013), “Wanamey: Árbol de vida” (2017). “Wawa Bebé” (2021). Ha venido desarrollando proyectos integrales como “Tejedores del sonido”, donde se enseña a hilar acompañadas del recurso del canto, “Conciertos de arrullo para bebés” y los círculos de expresión “El Cuerpo de la Voz”, para víctimas que han callado la violencia y “Voces y cantos para el arrullo” para fortalecer los vínculos afectivos de la familia con el bebé. Últimamente fue facilitadora del programa “Cartas y arrullos desde adentro” en el Penal de Qenqoro de Cusco a través del proyecto atravesando Muros liderado por Anahí Araoz. Actualmente viene componiendo cantos para obras escénicas y cine. Pueden ser apreciadas en “ Lliqllas infinitas” (2021), bajo la dirección Huandy Laguna y “K´anchay” (2022), que son cuentos salvavidas para niños y niñas bajo la inspiración de Luz Saenz y Adalid Rondan.
","img/Mujer_4.jpg","condeinfinito@hotmail.com","-13.522798","-71.97945447901128","https://www.youtube.com/embed/myEpMpTkVSY"),
	(5,"Natalya Eddem ","Lizarraga Conchatupa",1,"07/10/1982",NULL,"Con experiencia laboral desde el 2003 hasta la actualidad. Natalya Lizarraga ha trabajado en diferentes proyectos artísticos individuales y colectivos. Su trabajo consiste en estéticas como el surrealismo, surrealismo narrativo, que se ven reflejados en trabajos como: “Dulcinea”, “Huida a Egipto“, “Nativo“, parte del proyecto “Memoria 2014“ que constó de 4 exhibiciones realizadas en diferentes Centros Culturales del Cusco-Perú; otros trabajos con enfoque mayormente ecológico, de diferentes especies emblemáticas o en peligro de extinción a nivel nacional o internacional tenemos “Tigrillo“ 2015. Tambien en sus exposiciones se han enfocado en la cultura viva como son tradiciones orales, con obras como con la muestra realizada en la casa cultural Cusco-Perú , 2016. Otras expresiones artisticas que revalorando tradiciones y creencias mortuarios que se tienen en la actualidad que provienen desde la cosmovisión precolombina, con obras como “El condenado“, “Aparición“, “Ofrendas“ . Sobre mitos y leyendas, a nivel nacional e internacional nos deleita con obras como “El Minotauro“ 2004. Natalia Lizarraga ha tenido exposiciónes individuales y colectivas en el Perú como en el extranjero en paises como: México, Bruselas, Alemania y Estados Unidos. En el campo de la ilustración ha participando en proyecto como la publicación “Cuentos Aguarunas“ del Centro Guamán Poma de Ayala Cusco en 2010, tambien trabajo en el libro-cancionero “LLIQLLA“2021 con la Editorial SM Perú y colaborando en la portada del Álbum Musical Lliqlla de la misma cantautora Gladys Conde, Cusco, 2021.","img/Mujer_5.jpg","milimetricoinfinito@gmail.com","-13.522533","-71.966346","https://www.youtube.com/embed/-Q8TvP0NMos"),
	(6,"Antonieta","Conde Marquina",2,"10/05/1981",NULL,"Maestra y gestora intercultural. Magíster en Educación Intercultural Bilingüe. Madre, mujer e hija del ancestral Pueblo Quechua Kʼana de Layo, Cusco. Sus áreas de interés son: Intraculturalidad e interculturalidad, investigación y gestión intercultural en temáticas socioculturales, socioeducativas, sociolingüísticas y ciudadanía intercultural vinculados a los pueblos indígenas. En su trayectoria de proyección sociocultural, académica y de vida ha realizado publicaciones, presentaciones, actividades formativas y labores profesionales, con énfasis en lo testimonial, desde el enfoque intercultural dentro y fuera del Perú. Editora y correctora independiente, en quechua y castellano, de investigaciones científico sociales, literarias e informativas (desde 2003 hasta la actualidad). Es alumni/exbecaria de la Fundación Ford, FLACSO Argentina e Ibercultura Viva, FILAC y AECID.","img/Mujer_6.jpg","antonietacondemarquina@gmail.com","-14.48242077795887","-71.15427871932138","https://www.youtube.com/embed/aXVNtofplSk"),
	(7,"Lucy Magály","Fernández Medina",1,"24/11/1980",NULL,"Nació en la mítica ciudad del Cusco. Lugar en el que vivió hasta terminar sus estudios en la Universidad Andina (UAC). Es escritora, profesora de español como lengua extranjera y licenciada en Turismo. Ha llevado talleres de narrativa y escritura creativa en el Centro Cultural de la Pontificia Universidad Católica del Perú (PUCP), y durante varios años asistió a talleres con el escritor Alonso Cueto. El 2016 participó en la “Antología de microrrelatos eróticos II” de la editorial Altazor. El 2018 publica “Rojo” su primera novela de la mano con la editorial Forjadestino.
Cuenta la historia de una joven, quien es obligada a casarse con un rico y cruel hacendado a inicios de los años 30. 
El 2020 su novela “Otra selva para Mercedes” fue ganadora de los Estímulos Económicos para la Cultura (Apoyo a la Producción Editorial Peruana). Aquí narra las vicisitudes de una mujer en el ambiente hostil y genocida de la época del caucho. Y su cuento “Un trozo desprendido de la luna”, inspirado en Tomasa de Amat y García Mancebo será publicado en “21 Relatos sobre mujeres que lucharon por la independencia del Perú” de Petroperú.
","img/Mujer_7.jpg","artemisa_30@hotmail.com","-13.5367","-71.9049","https://www.youtube.com/embed/KKCDJW7P2P8"),
	(8,"Lenyan","Veka Pantigoso",1,"23/03/1989",NULL,"Poeta de Cusco, Docente de Arte, artista visual, actriz, performer y gestora cultural. Miembro- directora en Nina Warmikuna (2019) directora creativa en Guíame Sur Arequipa Organización Cultural, Lenyan Veka Art Concept, gestora en Cuéntame Poesía Online -En la voz del poeta (2020-2021). Ganadora del primer lugar del Concurso Literario La Copa de Doce Ángulos en la categoría de poesía (Arequipa, 2016), Mención honrosa en el festival de poesía Qosqo Tikarinanpaq, poemario Danzan las aves (2020). Finalista selección Video Raymi, categoría Video Arte muestra Universidad de Bellas Artes Granada (2018). 
Ha participado y sido antologada dentro y fuera de Perú, exponente en muestras multidisciplinarias io virtuales (2016-2022) (Perú, Bolivia, Chile, Ecuador, México y España). Organizadora y gestora del XXIII Festival de Poesía del Sur Andino” Enero en la Palabra”, Escape poético, Desaparición de la distancia (2020), Recital Poesía Amorosa (2019) Ciudad poética en el ombligo del mundo (2020) entre otros.","img/Mujer_8.jpg","lenyanvk@gmail.com","-13.5190517604757","-71.98053057","https://www.youtube.com/embed/tyrHBmP8MF0"),
	(9,"Emperatriz","Escalante Gutiérrez",1,"14/07/1942",NULL,"Realizo su estudios escolares en Educandas, sus estudios universitarios los realizó en la Universidad Nacional de San Antonio Abad del Cusco, en la Facultad de Educación, especialidad de Lengua y Literatura, a la par estudió en la Escuela Superior de Bellas Artes “Diego Quispe Ttito” de Cusco, especialidad de Dibujo y Pintura. Integró el Teatro Experimental Universitario de Cusco (TEUC), sus primeras publicaciones aparecen en revistas de esos años, como Maccana, órgano de la Federación Universitaria de Cusco (1966), y participó en exposiciones pictóricas. Posteriormente, junto a sus hermanas María Olinda y Carmen, integró la Agrupación Cultural René Ramírez Lévano (ACRRL) que desarrolló actividad cultural durante toda la década de 1970. Allí fue responsable del departamento de literatura, publicó cuentos, artículos y escribió libretos de teatro. Allí también formó un hogar con el músico y ensayista Pablo Ojeda Vizcarra, líder de ese grupo autónomo de artistas e intelectuales con pasión por el arte y compromiso social. Fue profesora contratada en Pucyura (provincia de Anta), en Acomayo y en el distrito de San Jerónimo. Ya como profesora nombrada, dedicó varios años a la enseñanza en el colegio de Maras, el colegio agropecuario Charcahuaylla de Urubamba, y finalmente en la ciudad del Cusco, en el Colegio Real “San Francisco de Borja”, donde culminó su labor docente, cesando luego de haber dedicado toda una vida a formar varias generaciones de jóvenes, a quienes alentó a interesarse por la literatura, la investigación y la cultura andina.
Esa combinación de trabajo literario y pedagógico le llevó a ganar varios premios: Obtuvo el segundo lugar en el concurso de letras para el Himno del colegio Garcilaso (1977), el tercer lugar en el Premio Fomento a la Cultura, categoría cuento, organizado por la Municipalidad del Cusco (1982), el segundo lugar en los II Juegos Florales Magisteriales de la Región Inka con el cuento “Los pastorcitos” (1990), mención honrosa en el género ensayo en los III Juegos Florales Magisteriales de la Región Inka (1991), con su propuesta “Talleres de lectura y redacción: ensayo pedagógico de experiencia didáctica en la enseñanza”. Fue finalista en el concurso de cuentos en quechua organizado por la Asociación Pukllasunchis (2000), y obtuvo mención honrosa en el Premio Regional de Cultura del INC, categoría cuento en quechua (2006). 
Casi la totalidad de su obra está dedicada al público infantil, a los estudiantes. Por eso también, su trabajo teatral y en artes plásticas los plasmó en talleres vacacionales, especialmente en la década del 2000, en la Asociación Roberto Ojeda Campana. Esos años también, junto a sus hermanas María Olinda Escalante (filósofa) y Carmen Escalante (antropóloga), integró la Asociación de Escritoras del Cusco.
","img/Mujer_9.jpg","cocherocusco@gmail.com","-13.519038430970400","-71.9801665424645","https://www.youtube.com/embed/4BGYioBebuo"),
	(10,"Iñakapalla","Chavez Bermudez",1,"20/06/1985",NULL,"Licenciada en Administración de la Universidad Andina del Cusco en el año 2014, con maestría en Antropología Social de la Universidad Nacional de San Antonio Abad de Cusco (2019). Es una gestora cultural independiente de proyectos de fotografía/ audiovisuales/ artes escénicas/ poesía/ pintura y música. Enlazando los temas de cultura y educación. Escribe poesía desde el año 2000 y sus poemas han sido incluidos en varias antologías a nivel nacional e internacional. Así mismo,es autora de diversos artículos y ensayos académicos de investigación, relacionados a los temas de gestión cultural, economía, educación y emprendimiento social.
Durante los años 2018- 2019, ha participado del proyecto de producción de audiovisuales del EMPODERARTE, dirigido por Karoline Pelikan, directora creativa de la casa PELIKAN PICTURES. 
También ha asesorando y organizando diversos eventos entre ellos, exposiciones de arte, fotografía, recitales de música con la Escuela de Violín Cusco, presentaciones de teatro dirigida a mujeres en el tema del cuidado del medio ambiente, violencia de género, brechas sociales, sororidad, entre otros. Ha sido ganadora de DAFO 2019- Estímulos económicos de fomento a la cultura y segundo lugar del “Concurso de poesía Taiwan 2010” Organizado por: Oficina Económica y Cultural Taiwan 2010 
","img/Mujer_10.jpg","iakachavezb@gmail.com","-13.537326","-71.903965","https://www.youtube.com/embed/-kjIlLVyXc4"),
	(11,"Liliana","Davila Jurado",3,"02/01/1982",NULL,"Liliana Davila Jurado nació en Huaro el año 1982, estudio la primaria y la secundaria en el colegio particular “Luz Casanova” - Lima, ingreso a la Universidad Nacional de San Antonio Abad del Cusco a la Facultad de Antropología, estudio 2 años y luego se traslado a la Universidad Federico Villareal, donde se graduó como antropóloga el 2006.
Realizo realizó varios cursos en Antropología y fotografía. Además realizó una maestría en Gestión Cultural, Patrimonio y Turismo.
Fue fundadora del museo “Piedras Sagradas” de Huaro, Quispicanchi, Cusco. Recibió la medalla junto a su padre en reconocimiento del museo por la Municipalidad Provincial de Quispicanchi. Participo de otros estudios e investigaciones en Lima. Actualmente viene trabajando en la primera publicación de su Poemario. 
","img/Mujer_11.jpg","lidaju@gmail.com","-13.690468","-71.640091","https://www.youtube.com/embed/Kbecwp_WeyE"),
	(12,"Cricia","Ochoa Huamanatica",1,"02/09/1994",NULL,"Cricia Ochoa estudió la carrera de Derecho y Ciencia Política en la Universidad Andina del Cusco. Se encuentra cursando la Maestría en Derecho Civil y Procesal Civil en la Universidad Nacional San Antonio Abad del Cusco. Es Conciliadora Extrajudicial. Especialista en Justicia Indígena y Derechos Humanos. Gestora de la segunda Comicteca del país para niños y jóvenes de la ciudad del Cusco. Columnista de Diario el Cusco, los semanarios Ideario, Qosqo Times, Cusco Noticias. Fue conductora y directora de la revista y programa cultural “Open Cusco”, Best Cable te Defiende, Inpecable, El Rincón de los Incomprendidos y Boquita de Caramelo.
Fue Parlamentaria joven por la Región Cusco en el Congreso de la República de Perú, Vocera regional de la Red Nacional de Mujeres Políticas Jóvenes y reconocida como Líder Internacional por la Organización Democrática Mundial. Actualmente es asesora jurídica y abogada en el Establecimiento de Medio Libre del Instituto Nacional Penitenciario, representante del Voluntariado Corporativo Renacer, Vocera de la Red de Mujeres sin Fronteras – Cusco, es asesora legal de la Gloriosa Federación Departamental de Campesinos del Cusco y se encuentra realizando investigaciones en el marco del Derecho Energético relacionado al cambio climático y Derecho Constitucional y Derechos Humanos. 
","img/Mujer_12.jpg","criciaochoahuamantica@gmail.com","-13.53738563780172","-71.9048227578276","https://www.youtube.com/embed/kjYjqZMe5UY"),
	(13,"Maggie","Velarde",1,"16/01/1993",NULL,"Margarita Estefani Oré Velarde es autora del libro de poemas El apu descalzo (Alastor Editores, 2021) con presentaciones en Cusco, Lima, Arequipa, Ica y Chimbote. Este fue escogido para el stand de Perú en la FIL Guadalajara 2021 y para la FIL Buenos Aires 2022. También publicó el libro de cuentos Breves historias de los efímeros (2020).
Además es co-autora del cortometraje poético TRENZAR, junto a las artistas Almendra Vivanco y Margarita León (2021).
Ha colaborado con el programa Lima Lee de la Municipalidad de Lima; con el programa Visita al Autor del Ministerio de Cultura; y, con el programa Mi Biblioteca mi prioridad de la Biblioteca Nacional del Perú.
Ha publicado poemas en diversas revistas literarias y ha participado en festivales nacionales e internacionales.
","img/Mujer_13.jpg","maggieov33@gmail.com","-13.517288","-71.962605","https://www.youtube.com/embed/GSaqeTjEoGU"),
	(14,"Gabriela","Caballero Delgado",4,"24/03/1977",NULL,"Gabriela Caballero Delgado radica en Tacna más de 30 años. Es profesora de Lengua y Literatura por la Universidad Jorge Basadre Grohmann de Tacna, casa superior donde también ha concluido estudios de maestría en Gerencia y Administración de la Educación.
Fue coeditora de la revista de literatura Utopía. Jefa de redacción de La yegua colorá. Actualmente es asesora literaria de la editorial Cuadernos del Sur. Fue finalista en la XIV Bienal de Cuento Premio Copé 2006 por la obra “La metamorfosis de Alejandra” y ganó el primer premio del I Concurso Nacional de Cuento de ELECTROPUNO 2006. Sus cuentos han aparecido en algunas antologías como Historias de arena -cuentos playeros de Tacna- (Cuadernos del Sur, 2012); El cuento peruano 2000 – 2010 (PETROPERÚ, 2013); Narrativa en Tacna (Cuadernos del Sur, 2018); 21 Relatos sobre la Independencia del Perú (PETROPERÚ, 2019); MARIO Y LOS ESCRIBIDORES 27 relatos sobre el universo vargasllosiano (Altazor, 2019); Cuentos peruanos de la pandemia (Mascapaycha, 2021); entre otros.
","img/Mujer_14.jpg","gcaballerod@gmail.com","-13.919182763550886","-71.6832945542301","https://www.youtube.com/embed/A0mIc4-wf8I");

INSERT INTO site_web_publicacion(id,titulo,isbn,categorizacion,fecha,descripcion,mujer_id,link_imagen,titulo_disponible,link_disponible) VALUES
	(1,"Sueño Índigo","9786124751028","Cuentos","2018","Libros que contiene dos historias tiernas, acompañadas de espectaculares ilustraciones que te transportarán junto a los protagonistas.",1,"img/Mujer_1_Libro1.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(2,"Colores",NULL,"Cómic","2020","La autora nos cuenta una pequeña anécdota de su infancia en el jardín de su abuela.",1,"img/Mujer_1_Libro2.jpg","Plataforma Behance","https://www.behance.net/gallery/125265469/COLORS-COMIC-Colores-Comic"),
	(3,"Pasado",NULL,"Cómic","2021","Cómic Ganador del Concurso Internacional de Historieta “La sociedad en tiempos de Pandemia” del Festival Virtual Internacional de las artes “Qosqo T’ikarinampaq 2020” Organizado por la Municipalidad del Cusco.",1,"img/Mujer_1_Libro3.jpg","Plataforma Behance","https://www.behance.net/gallery/124964849/PASADO-por-Adriana-Cule-AKA-Madivera"),
	(4,"Antología Ángeles y Demonios",NULL,"Cuentos","1998","Antología organizada por la Asociación Centro Cultural Cusco.",2,"img/Mujer_2_Libro1.jpg","Esta publicación no esta disponible.",NULL),
	(5,"Poemario Acidulce","200901791","Poemario","2009","Éste es su primer poemario, como el título, un cúmulo de dulces y ácidas experiencias",2,"img/Mujer_2_Libro2.jpg","Sitio Web Ana María Milla","https://anamaria.pro/acidulce/"),
	(6,"Mil Poemas a César Vallejo: Una gesta de amor universal",NULL,"Poemario","2012","Ana María Milla participa en esta antología con su poema en la página 349, esta publicación es una recopilación hecha por Alfred Asís Antología-Recopilación-Escritoras, Escritores-Poetas del Mundo.",2,"img/Mujer_2_Libro3.jpg","Enlace Drive","https://drive.google.com/file/d/1k0S8eXwEdFe0iNi_0PyDisx1lE-LiT0c/view?usp=sharing"),
	(7,"La hija del bosque",NULL,"Poemario","2019","La Hija del Bosque es su segundo poemario, y el primero la colección El Retorno de los paganos, colección de publicaciones sobre el retorno a la naturaleza y el viaje interior que toma de pretexto de los viajes físicos hacia otra comprensión del mundo y del universo.",2,"img/Mujer_2_Libro4.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(8,"Poemic: El atardecer del fin del mundo",NULL,"Cómic","2019","Poemic, es una producción que busca fusionar un poema con el arte del cómic. Con el título El atardecer del Fin del Mundo, es un viaje épico en un mundo en guerra, hacia la esperanza de un mundo mejor. Magistralmente ilustrado por el equipo de Qosqomic, liderado por el artista Fabricio Rivas Mar.",2,"img/Mujer_2_Libro5.jpg","Sitio Web Ana María Milla","https://anamaria.pro/poemic/"),
	(9,"Documentos para la historia eclesiástica de Apurímac. Análisis histórico al documento de la peregrinación de Sebastián Quimichi, siglo XVII","27098680","Artículo de revista","2020","El presente trabajo analiza la peregrinación de Sebastián “Quimichi”, a partir de la documentación que pertenece al archivo histórico del Santuario de Cocharcas, específicamente al documento denominado “Relación de la imagen de Nuestra Señora que está en este pueblo de Cocharca hecha por el licenciado don Pedro Guillén de Mendoza en 20 de julio de 1625 años”.",3,"img/Mujer_3_Libro1.jpg","Revista Riqch’ariy Vol. 1, N° 01, 2020. pp. 147-178","https://www.academia.edu/44910438/REVISTA_RIQCH_ARIY_No_01"),
	(10,"El archivo del Santuario de Cocharcas: historia, catalogación y transcripción paleográfica siglos XVI-XX.","287307","Artículo de revista","2017","El motivo del presente trabajo es la difusión de los fondos documentales del Archivo Histórico del Santuario de Cocharcas, cuya recuperación y organización se inició el 2009 a través del entonces Instituto Nacional de Cultura Cusco (INC), institución que se encontraba restaurando el citado santuario. Con el trabajo efectuado, que fue la Puesta en Valor del archivo, se logró poner al servicio libros de cofradías, fábrica, inventarios, empadronamientos, testamentos y libros sacramentales (entierros, bautizos, matrimonios y confirmaciones), además de libros de inicios del siglo xx como litigación de tierras, peticiones y solicitudes, entre otros, que dan cuenta de la vida social, religiosa y cultural del santuario y la doctrina de Cocharcas, desde finales del siglo XVI hasta inicios del XX.",3,"img/Mujer_3_Libro2.jpg","Revista del Archivo General de la Nación N°32, 2017, págs. 287-307","https://revista.agn.gob.pe/ojs/index.php/ragn/issue/view/1/4"),
	(11,"Espacios de inclusión y exclusión: Etnias, ayllus y cofradías en la conformación de la doctrina eclesiástica de Cocharcas 1570-1614.","9786124544637","Artículo de revista","2013","El presente artículo se enmarca en el difícil proceso de reorganización social y religiosa que las poblaciones indígenas padecieron dentro de la región de Huamanga en la coyuntura finisecular del siglo XVI. Nuestra preocupación por comprender dichas reorganizaciones obedece a un doble interés, primero dar cuenta de la conformación del espacio social de la doctrina de Cocharcas, y segundo realizar un análisis de las relaciones interétnicas y las nociones de inclusión/exclusión a partir de la implantación de la institución de la cofradía, convirtiéndose en el medio de mayor eficacia para canalizar y viabilizar los intereses colonial étnicos locales de poder para así ganarse un espacio dentro de la nueva sociedad colonial que se conformaba.",3,"img/Mujer_3_Libro3.jpg","Cuadernos de Investigación Universitaria, 2013, núm. 01. 01 págs. 45-70","https://www.academia.edu/44912519/CUADERNOS_DE_INVESTIGACI%C3%93N_N_01"),
	(12,"El Santuario de Cocharcas: Construcción, clero secular y participación indígena (1611-1680)",NULL,"Articulo de revista","2013","El presente artículo se enmarca en el difícil proceso de reorganización social y religiosa que las poblaciones indígenas padecieron dentro de la región de Huamanga en la coyuntura finisecular del siglo XVI. Nuestra preocupación por comprender dichas reorganizaciones obedece a un doble interés, primero dar cuenta de la conformación del espacio social de la doctrina de Cocharcas, y segundo realizar un análisis de las relaciones interétnicas y las nociones de inclusión/exclusión a partir de la implementación de la cofradía, convirtiéndose en el medio de mayor eficacia para canalizar y viabilizar los intereses colonial étnicos locales de poder para así ganarse un espacio dentro de la nueva sociedad colonial que se conformaba.",3,"img/Mujer_3_Libro4.jpg","Arquitextual N°02, Huancayo, Diciembre 2013, pp 82-102.","https://issuu.com/gusstockconchaflores/docs/arquitextual_2"),
	(13,"Investigación histórica del Santuario de Cocharcas y el Archivo Arzobispal de Abancay.",NULL,"Artículo de revista","2014",NULL,3,"img/Mujer_3_Libro5.jpg","Red de Archivos y Bibliotecas Históricas del Perú","http://archivosybibliotecasdelperu.blogspot.com/2014/03/investigacion-historica-del-santuario_1784.html"),
	(14,"RIQCH´ARIY",NULL,"Edición","2006, 2008, 2020, 2021","Revista de corte social con carácter multidisciplinario producido por el círculo de estudios del mismo nombre pertenecientes a la Facultad de Ciencias Sociales de la Universidad Nacional de San Antonio Abad del Cusco (UNSAAC).",3,"img/Mujer_3_Libro6.jpg","Revista Riqch’ariy ","https://revistariqchariy.com/"),
	(15,"CUADERNOS DE INVESTIGACIÓN UNIVERSITARIA",NULL,"Edición","2012, 2013, 2014","Revista exclusivo para jóvenes y egresados de las diversas carreras profesionales, con el objetivo de dar a conocer los resultados de las investigaciones científicas y los procesos de transferencia tecnológica que se da en la Universidad de San Antonio Abad del Cusco (UNSAAC)",3,"img/Mujer_3_Libro7.jpg","Vicerrectorado de Investigación de la Universidad de San Antonio Abad del Cusco (UNSAAC)","http://vrin.unsaac.edu.pe/"),
	(16,"II SEMANA DE INVESTIGACIÓN",NULL,"Edición","2014","Publicación que conjuga un conjunto de actividades de capacitación y promoción de la investigación científica con el objetivo de generar un espacio plural de debate en relación a la invención, innovación e investigación científica, tecnológica y humanista en la región Cusco con participación de expertos, profesores y estudiantes universitarios de la UNSAAC y el país.",3,"img/Mujer_3_Libro8.jpg","Vicerrectorado de Investigación de la Universidad de San Antonio Abad del Cusco (UNSAAC)","http://vrin.unsaac.edu.pe/"),
	(17,"VADEMÉCUM",NULL,"Edición","2013-2014","El Vicerrectorado de Investigación de la Universidad Nacional de San Antonio Abad del Cusco presenta la publicación VADEMÉCUM DE INVESTIGACIÓN FEDU 2013-2014, que da continuidad a la difusión de las diferentes investigaciones realizadas por grupos de docentes activos y jubilados durante el bienio señalado, los mismos fueron financiados con el Fondo Especial de Desarrollo Universitario (FEDU)",3,"img/Mujer_3_Libro9.jpg","Vicerrectorado de Investigación UNSAAC-VADEMÉCUM - Recursos Digitales","http://vrin.unsaac.edu.pe/publicaciones/1/vademecum-fedu-20132014.html"),
	(18,"Antología Poética del Cusco",NULL,"Poemario","2007","Gladys Conde es acreedora de mención honrosa en poesía por el Premio Regional de Cultura de Cusco (2006), publicándose sus poemas en “Antología Poética del Cusco” realizado por el INC en el 2007.",4,"img/Mujer_4_Libro1.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(19,"Juego y silencio","9786124544811","Poemario","2009","Poemario de 26 poemas cortos, algunos lúdicos otros más serios; donde la poeta relaciona el proceso de creer con metaforas de la naturaleza, el juego y el silencio.",4,"img/Mujer_4_Libro2.jpg","Esta publicación no esta disponible.",NULL),
	(20,"Lliqlla: El canto de la abuela","9786123169701","Cancionero","2020","Gladys Conde ha bebido de la fuente de nuestros ancestros para crear estas maravillosas canciones para el arrullo y el sueño; para crecer y sanar. Los once cantos que incluye este libro nos hacen contemplar la armonía cósmica que reina entre plantas y animales; entre el cielo y la tierra. Las canciones además vienen acompañadas de las luminosas pinturas de la artista plástica Natalya Lizárraga.
",4,"img/Mujer_4_Libro3.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(21,"Cancionero para bebés 2. Colección Tuctupillín","9786124456237","Cancionero","2020","Gladys Conde es parte de este proyecto con 3 canciones. El programa Bebetecas de la Casa de la Literatura Peruana presenta el segundo volumen de Cancionero para bebés. Esta antología reúne más de 30 arrullos, juegos de palabras y canciones que involucran el cuerpo para propiciar el primer vínculo musical de los bebés con el lenguaje. 

",4,"img/Mujer_4_Libro4.jpg","La Casa de la Literatura Peruana","http://www.casadelaliteratura.gob.pe/segundo-cancionero-del-programa-bebetecas/"),
	(22,"Cuentos Aguarunas","DL 2011 00716","Cuentos","2010","Los dos mitos publicados en este folleto han sido tomados del libro Mitos e historias aguarunas de José Luis Jordana Laguna (Retablo de papel ediciones. Lima. 1974); esta publicación trabajada por Guaman Poma de Ayala trae a la vida estos hermosos mitos mediante la ilustración de Natalya Lizarraga.",5,"img/Mujer_5_Libro1.jpg","Plataforma Yumpu","https://www.yumpu.com/es/document/read/14596588/cuentos-aguarunas-en-espanol-guaman-poma-de-ayala"),
	(23,"Identidad, tradición oral y cosmovisión basada en el ecosistema en Perú: reflexiones estéticas desde el surrealismo",NULL,"Artículo de revista","2022","En el presente artículo la ilustradora explica: Lejos de proponer una visión romanizada de la tradición oral y la cosmovisión ancestral, pretendo brindar reflexiones desde mi práctica artística personal y desde la corriente estética del surrealismo sobre los elementos claves de la identidad y los ecosistemas en el Perú. Mucha de la influencia e inspiración nace tanto de artistas y artesanos locales como internacionales. Me enfoco en corrientes que nacieron en la colonia, como es la reconocida Escuela Cusqueña, que tiene como representantes a pintores como Diego Quispe Tito, o el pintor Italiano Bernardo Bitti. Cabe resaltar que los trabajos de la Escuela Cusqueña en mayoría son obras de pintores originarios y mestizos. Obras sacras como las del Corpus Christi siglo XVII de autor anónimo o la obra Virgen del Carmen del siglo XVII, que por su composición se asocia a la representación de la Pachamama, son importantes como antecedente de la pintura actual peruana enfocada en lo tradicional y la ecología",5,"img/Mujer_5_Libro2.jpg","Revista de Ecología Política","https://www.grassrootsjpe.org/publications/visual-essay/identidad-tradicion-oral-y-cosmovision-basada-en-el-ecosistema-en-peru-reflexiones-esteticas-desde-el-surrealismo/?fbclid=IwAR2bXxfO7MwyYIIsEXr961FJz4A8cCgEhcZPoPRSHNzykUUBurOd9u-Okzw"),
	(24,"Lliqlla: El canto de la abuela","9786123270254","Cancionero","2020","Natalya Lizarraga apoya con sus hermosas ilustraciones a Gladys Conde en este cancionero para niños, los once cantos nos hacen contemplar la armonía cósmica que reina entre plantas y animales; entre el cielo y la tierra.",5,"img/Mujer_5_Libro3.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(25,"Usos del quechua en Layo, K´ana suyupi, Cusco","9789995415914","Libro de investigación","2014","Este libro explora la situación sociolingüística del uso del quechua en la comunidad de Taypitunga, Layo, Cusco. Los datos fueron recopilados a través del método etnográfico. Este método posibilitó conocer la versión directa de los hablantes, y en su propio contexto, acerca del proceso actual que el quechua presenta. Las entrevistas y las observaciones de las interacciones de uso del quechua contaron con la participación de jóvenes colegiales y por extensión a los hablantes de la comunidad en general. Los ámbitos que se tomaron como referencia fueron: el hogar, el colegio y la comunidad",6,"img/Mujer_6_Libro1.jpg","DocPlayer","https://docplayer.es/90780283-Usos-del-quechua-en-layo-k-ana-suyupi-cusco.html"),
	(26,"Oro hate emändoya Wachiperi : Diccionario Wachiperi Castellano / DDC-Cusco","9786124686528","Corrección de estilo","2014","(Antonieta realiza la corrección de estilo) El Ministerio de Cultura presentó el Diccionario Wachiperi: Oro Hate Emändoya. La lengua wachiperi, hablada en la provincia de Paucartambo, es una variedad del harakbut. Este diccionario recoge la sabiduría, los conocimientos y expresiones propias de la cosmovisión amazónica de las comunidades nativas de Santa Rosa de Huacaria y Queros Wachiperi; y adquiere una singular importancia para los wachiperi del siglo XXI, interesados en revertir el proceso de debilitamiento en que se encuentra su pueblo ante la disminución de la práctica de su lengua.",6,"img/Mujer_6_Libro6.jpg","Biblioteca Central DDC-Cusco","http://biblioteca.culturacusco.gob.pe/cgi-bin/koha/opac-detail.pl?biblionumber=3948"),
	(27,"Poesía (Quechua y Castellano). Antología de Ganadores de la Categoría “C” : Premio Regional de Cultura, 2015 / Dirección Desconcentrada de Cultura Cusco","DL 201603534","Corrección de estilo","2015","(Antonieta realiza la corrección de estilo en quechua ). Antología de poemas en quechua y castellano de los ganadores de la Categoría “C”. Entre los poetas de esta antología tenemos: Gladis Naty Valencia Rosell, Huchuy harawikunata; Rocío Cjuiro Mescco, Qaqarumicha. Poesía en castellano: Pável Ugarte Céspedes, Repatriación de las aves; Elvis David Quispe Altamirano, Visitame siempre en octubre; Martin Castillo Collado, Primera Dosis; Jhon Hansel Choque Condori, La Palabra no hace el amor, sino la ausencia",6,"img/Mujer_6_Libro5.jpg","Biblioteca Central DDC-Cusco","http://biblioteca.culturacusco.gob.pe/cgi-bin/koha/opac-detail.pl?biblionumber=8894"),
	(28,"Quechua, idioma que puede hacer retornar la vida de comunidad: Runasimiqa ayllumanmi kutichinman","9789568416461","Ensayo","2016","Este ensayo trata sobre la inserción tímida de este proceso reivindicativo y justiciero en el contexto y escenario histórico, simbólico, práctico, institucional, familiar, personal",6,"img/Mujer_6_Libro2.jpg","Ariadnaediciones","https://ariadnaediciones.cl/index.php?option=com_content&view=article&layout=edit&id=153"),
	(29,"Poesía Súper Contemporánea de Perú y Estados Unidos.","9789569853104","Traducción","2017","(Antonieta participa en el grupo de traductores de esta obra) Poesía súper contemporánea de Perú y Estados Unidos es un libro sensual y necesario. Entre sus páginas se encuentran las voces más destacadas del movimiento literario alt-lit de Estados Unidos con una intensa muestra de poesía peruana contemporánea: individual y colectiva, del campo y la ciudad, tradicional y de vanguardia al mismo tiempo.",6,"img/Mujer_6_Libro7.jpg","Libreria Búho Azul","https://www.facebook.com/buhoazulcusco"),
	(30,"Revista Saqsaywaman N°10",NULL,"Corrección de estilo","2018","(Antonieta realiza la corrección de estilo en quechua ) Nuevos aportes a la Arqueología del Periodo Formativo del Cusco en Marcavalle, Minaspata y Kullupata.",6,"img/Mujer_6_Libro4.jpg","Esta publicación no está disponible.",NULL),
	(31,"Balance preliminar en torno a avances, desafíos y oportunidades de la consulta previa en el Perú","9786124740831","Ensayo","2018","El trabajo de investigación ofrece una mirada panorámica de la consulta previa en cinco apartados. Los procesos vinculados a la consulta previa vislumbran el punto de quiebre que dio origen a los diferentes eventos, etapas, acuerdos y desacuerdos que sirvieron de preámbulo a la promulgación de la ley y su reglamento.",6,"img/Mujer_6_Libro3.jpg","Centro de Estudios Constitucionales (CEC) Colección  “Derecho y Sociedad” 2017","https://www.tc.gob.pe/wp-content/uploads/2018/10/Justicia-e-interculturalidad.pdf"),
	(32,"5to Festival Caravana de Poesía Cusco - Ayacucho","9786124770265","Poemario","2018","Antología de poemas en castellano y quechua.",6,"img/Mujer_6_Libro8.jpg","Esta publicación no está disponible.",NULL),
	(33,"Relato Puriy kutiy (El viaje del retorno)",NULL,"Cuento","2012","La autora nos comenta que este relato fue publicado en Noqanchis No. 5. revista bilingüe quechua-asháninka, 2012",6,"img/Mujer_6_Libro9.jpg","Esta publicación no está disponible.",NULL),
	(34,"Rojo","9786124788512","Novela","2018","En el año 1932, Matilde tiene 15 años y tras la muerte de su padre, es ofrecida en casamiento a Artemio Urbina, hombre adinerado que dedica su vida a viajes y fiestas. Rojo es la historia del mundo interior de Matilde, pero también de su encuentro con el diario de Lavinia Vigorou, primera esposa de Artemio e importante pianista de la época cuyos escritos revelan libertad y cultos esotéricos, fragmentos íntimos que abren las puertas a un paisaje sensorial y espiritual, que cogen la mano de la protagonista para intentar salvarla del vacío.",7,"img/Mujer_7_Libro1.jpg","Editorial Forjadestino","https://www.facebook.com/forjadestino/"),
	(35,"De los vientos o la muerte","9786124788574","Novela","2021","Mercedes tenía dieciséis años cuando un hombre vestido con un terno blanco fue a recogerla para llevarla por primera vez a la Amazonía. Al pasar los treinta, siente que jamás podrá acostumbrarse a vivir en aquel lodazal olvidado del mundo. Busca aferrarse a algo, a alguien, pero está sola. Rodeada de un interminable abismo.",7,"img/Mujer_7_Libro2.jpg","Editorial Forjadestino","https://www.facebook.com/forjadestino/"),
	(36,"Un trozo desprendido de la luna",NULL,"Relato","2021","Lucy Fernandez traza desde los hábitos y costumbres de Tomasa Amat y García Mancebo dama de la sociedad involucrada en la causa independentista y nieta de famosa Perricholi, el recorrido de San Martín desde su desembarcación en Paracas hasta la proclama de la independencia en Lima. (Parte de 21. Relatos sobre mujeres que lucharon por la Independencia del Perú)",7,"img/Mujer_7_Libro3.jpg","Petro Perú Gestión Cultural","https://cultura.petroperu.com.pe/biblioteca-cope/veintiun-relatos-volumen-dos/"),
	(37,"La cocina",NULL,"Relato Erótico","2016","Lucy Fernandez participa en la Antología de microrrelatos eróticos II titulado “69”, trabajo seleccionado por Carolina Cisneros para editorial Altázor. Una cuidadosa edición en formato pequeño que reúne a 69 escritoras que presentan 69 microrrelatos, en tono erótico, con la peculiaridad de estar escritos en 69 palabras.",7,"img/Mujer_7_Libro4.jpg","Esta publicación no está disponible.",NULL),
	(38,"La flor en que amaneces. Edición V.","DL ZU2021000284","Antología","2021","Lenyan Veka participa en esta antologia poetica de Serie Asteroide (Venezuela) con sus poemas: “Figura en Verso”, “Amanece”, “Sobre el cuerpo”.",8,"img/Mujer_8_Libro1.jpg","Issuu","https://issuu.com/edicionesazalea/docs/la_flor_en_que_amaneces_-_n_mero_cinco"),
	(39,"Voces de la poesía peruana","9786124868603","Antología","2021","Lenyan Veka participa en esta antologia poetica realizada por Helard Fuentes. Es una obra que reúne la muestra poética de destacados escritores a nivel nacional, así como aquellas voces emergentes en la contemporaneidad, planteando un sentido integrador propuesto por su autor en base a cuatro criterios: intercultural, interregional, interdisciplinario e intergeneracional.",8,"img/Mujer_8_Libro2.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(40,"En octubre si hay milagros, Antología Poética",NULL,"Antología","2021","Lenyan Veka participa en esta antologia poetica de la editorial Z3ntauro",8,"img/Mujer_8_Libro3.jpg","Esta publicación no está disponible.",NULL),
	(41,"Tu voz existe, Antología Poética",NULL,"Antología","2020","Lenyan Veka participa en esta antologia poetica realizada por Colectivo Femenino Cultural Atenea. Siendo este un homenaje a Adela Montesinos.",8,"img/Mujer_8_Libro4.jpg","Colectivo Femenino Cultural Atenea","https://www.facebook.com/Colectivo-Femenino-Cultural-Atenea-108899337148451/"),
	(42,"Tu voz existe, Antología Poética",NULL,"Antología","2019","Lenyan Veka participa en esta antologia poetica realizada por Colectivo Femenino Cultural Atenea. Siendo este un homenaje a Carmela Nuñez Ureta.",8,"img/Mujer_8_Libro5.jpg","Colectivo Femenino Cultural Atenea","https://www.facebook.com/Colectivo-Femenino-Cultural-Atenea-108899337148451/"),
	(43,"Revista Watanay. Edición abril 2021. (Cusco).",NULL,"Revista","2021","Lenyan Veka tiene su participación en esta revista Watanay, bastion de la kultura Kuzko, ABRIL de 2021 BRIL de 2021
Kuzqo - Perú año 4 - número 8 4to. temporal (edixión modorra).",8,"img/Mujer_8_Libro6.jpg","Enlace Drive","https://drive.google.com/drive/folders/1L-XBXdF5Qjz-5ROkk2v4VomnMhY82ANs"),
	(44,"Aislados·Dosis de poesía para tiempos inciertos","9786124799228","Antologia","2020","Lenyan Veka participa en esta antologia poetica. En un año ciertamente inesperado y difícil, nos hemos dado a la tarea de salvar las distancias y unirnos más a través del verbo hecho arte: la poesía. Fruto de ese esfuerzo y hermandad es esta primera dosis digital que reúne a 89 voces contemporáneas de diversas nacionalidades, quienes no han dejado ni dejarán de forjar la palabra a pesar de los tiempos adversos.",8,"img/Mujer_8_Libro7.jpg","Dendro Casa Editorial Independiente","https://dendroeditorial.wordpress.com/2020/08/20/aislados-dosis-de-poesia-para-tiempos-inciertos/"),
	(45,"Crudo, revista de poesía e ilustración # 2. Editorial",NULL,"Revista","2020","Es una publicación de Loko El Gato la Editorial/Difusora. Con la participación de los ilustradores Favio Carranza y Chontano Gamarra de Bolivia. Participan con poesía: Cesar Hidalgo (Chile), Jose Villanueva (Bolivia), Lenyan Veka (Perú), Inti Villasante (Bolivia), Pep Balcárcel (Guatemala), Shantra Mantra (Bolivia), Pavel Ugarte (Perú), Ana Medinacelli (Bolivia), Toño Niño (Colombia). Crudo #2 desde Bolivia para el mundo.",8,"img/Mujer_8_Libro8.jpg","Loko: El gato","https://www.facebook.com/LokoElGato"),
	(46,"El color de las palabras",NULL,"Antología","2019","Lenyan Veka participa en esta antologia poetica. Antología de Colección Festival Internacional de Poesía Joven Jauría Palabras 2019 (Santa Cruz, Bolivia).",8,"img/Mujer_8_Libro9.jpg","Esta publicación no está disponible.",NULL),
	(47,"5to Festival Caravana de Poesía Cusco - Ayacucho.","9786124770265","Antologia","2018","Lenyan Veka participa en esta antologia poetica. Antología de poemas en castellano y quechua.",8,"img/Mujer_8_Libro10.jpg","Esta publicación no está disponible.",NULL),
	(48,"Mixtura de poesía en el ensarte de las artes.",NULL,"Antologia","2018","Lenyan Veka participa en esta antologia poetica.Mixtura de poesía en el ensarte de las artes es una edición conmemorativa de los 25 años del Festival del Arco iris, Cusco.",8,"img/Mujer_8_Libro11.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(49,"Enero en la Palabra XVIII Festival de poesía del sur andino.",NULL,"Antologia","2014","Lenyan Veka participa en esta antologia poetica. “Enero en la Palabra”, gran encuentro de poetas realizado cada año en enero, con la participación poetas cusqueños, nacionales e internacionales, con el apoyo de la Dirección Desconcentrada de Cultura Cusco.",8,"img/Mujer_8_Libro12.jpg","Esta publicación no está disponible.",NULL),
	(50,"Enero en la Palabra XIX Festival de poesía del sur andino, En el hemisferio femenino.",NULL,"Antologia","2015","Lenyan Veka participa en esta antologia poetica. “Enero en la Palabra” gran encuentro de poetas realizado cada año en enero, con la participación poetas cusqueños, nacionales e internacionales, con el apoyo de la Dirección Desconcentrada de Cultura Cusco. Enero en la palabra XIX, tiene dos prioridades visualizar el trabajo de óetas mujeres y ña poesia en lenguas originarias.",8,"img/Mujer_8_Libro13.jpg","Esta publicación no está disponible.",NULL),
	(51,"Enero en la Palabra XXII Festival de poesía del sur andino.",NULL,"Antologia","2018","Lenyan Veka participa en esta antologia poetica. “Enero en la Palabra XXII”, gran encuentro de poetas realizado cada año en enero, con la participación poetas cusqueños, nacionales e internacionales, con el apoyo de la Dirección Desconcentrada de Cultura Cusco.",8,"img/Mujer_8_Libro14.jpg","Esta publicación no está disponible.",NULL),
	(52,"7to Festival Caravana de Poesía Pisco-Lima-Huancayo",NULL,"Antologia","2022","Lenyan Veka participa en esta antologia poetica. Antología de poemas en castellano y quechua.",8,"img/Mujer_8_Libro15.jpg","Esta publicación no está disponible.",NULL),
	(53,"Narradores cusqueños : Estudio Preliminar, antología y notas",NULL,"Antología","1984","El cuento de Emperatriz Escalante, “La bruja buena” fue incluido en la Antología de Narradores Cusqueños de Rubén Sueldo Guevara (1984)",9,"img/Mujer_9_Libro1.jpg","Biblioteca Central DDC-Cusco","http://biblioteca.culturacusco.gob.pe/cgi-bin/koha/opac-detail.pl?biblionumber=567"),
	(54,"II Juegos Florales Magisteriales de la Región Inka",NULL,"Antologia","1990","Emperatriz Escalante participa en esta antologia con su cuento “Los pastorcitos”, con el cual obtiene el 2do lugar.",9,"img/Mujer_9_Libro2.jpg","Esta publicación no está disponible.",NULL),
	(55,"El nuevo Pinocho",NULL,"Cuentos","2005","En este breve libro hay 5 cuentos:El Nuevo Pinocho, El Trovador, La Bruja Buena, Los Vampiros, El Curandero.",9,"img/Mujer_9_Libro3.jpg","Esta publicación no está disponible.",NULL),
	(56,"Antologia de Cuentos en Quechua",NULL,"Antologia","2006","Emperatriz Escalante obtuvo mención honrosa en el Premio Regional de Cultura del INC, siendo publicado en esta antología.",9,"img/Mujer_9_Libro4.jpg","Esta publicación no está disponible.",NULL),
	(57,"MIS LECTURAS PREFERIDAS I – Obra en dos idiomas. (3er grado)","9786124654992","Antología","2016","Algunos escritos de Emperatriz Escalante aparecen en esta selección de cuentos, narraciones, mitos y leyendas, para lectores de 3er grado de primaria. Obra que crea hábitos de lectura y despierta el interés en los niños por los libros. Inculcan valores como la honradez, disciplina, el orden, la solidaridad, el desprendimiento, el compromiso, el respeto, etc.",9,"img/Mujer_9_Libro5.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(58,"MIS LECTURAS PREFERIDAS II – Obra en dos idiomas. (4to grado)","9786124732706","Antología","2016","Algunos escritos de Emperatriz Escalante aparecen en esta selección de cuentos, narraciones, mitos y leyendas, escogidos para lectores de 4to grado; obra que ayuda a crear hábitos de lectura e interés por los libros. Inculcan valores como la honradez, la estima, la disciplina, el orden, la solidaridad, el desprendimiento, el compromiso, el respeto, etc. Contiene, además, interculturalidad, inclusión social, identidad regional y nacional, costumbres, tradiciones y orgullo por lo nuestro.",9,"img/Mujer_9_Libro6.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(59,"MIS LECTURAS PREFERIDAS I – Obra en dos idiomas. (5to grado)","9786124732713","Antología","2016","Algunos escritos de Emperatriz Escalante aparecen en este volumen que compila una selección de temas entre cuentos, narraciones, mitos y leyendas para lectores del 5to grado de primaria; es una obra que promueve y crea hábitos de lectura, consolida el interés por los libros, refuerza la capacidad de analizar y comprender de mejor manera lo leído. Son lecturas que inculcan los distintos valores humanos dentro de los conceptos de interculturalidad e inclusión social. Es una obra que rescata identidad regional y nacional, revalora las costumbres, tradiciones y genera orgullo por lo nuestro.",9,"img/Mujer_9_Libro7.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(60,"Los vampiros","9786125001115","Cuento","2020","Una familia de las zonas alto andinas y apremiada por las necesidades, decide trasladarse y vivir en un pequeño lugar ubicado en plena ceja de selva; sin embargo, las raras muertes de sus animales, la falta de apoyo médico oportuno, el riesgo de sus propias vidas, harán que decidan afrontar directamente al causante de tantas muertes y el que tendrá un final sorprendente.
Esta lectura enseña lo importante de evaluar y hallar soluciones para luego tener el valor de ejecutarlas.",9,"img/Mujer_9_Libro8.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(61,"El libro = Qelqasqa patara","9786125001061","Cuento","2020","Un joven apasionado de los libros, descubre un ejemplar al cual no puede acceder; impulsado por su deseo de poder leerlo, de tener en sus manos y deleitarse con la lectura de dicha obra, lo hará cometer un grave error. Los resultados de su proceder, no se dejan esperar, y son acontecimientos lamentables. Esta narración, enseña a más de valores, a ser perseverante, pero también, paciente, y ante las circunstancias adversas, a ser prudente.",9,"img/Mujer_9_Libro9.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(62,"Suyaypaq Takin","9786124392290","Cuento","2020","El libro Suyaypaq Takin. Cuentos y poemas en quechua responde a ambas necesidades. Incluye dos cuentos finalistas en concursos regionales, que fueron publicados por las respectivas instituciones organizadoras de esos certámenes. Esta edición reúne estos y otros cuentos de la autora, constituyendo un cuerpo de relatos bilingües, que describen los valores, dificultades y retos de los pueblos andinos contemporáneos, expresando la belleza y potencia de esta milenaria cultura. También trae nueve poemas de la autora, todos en runasimi (quechua), que muy bien pueden acompañar actividades escolares por su temática regional, histórica, vivencial y reflexiva.",9,"img/Mujer_9_Libro10.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(63,"Tatiana","9786125001139","Cuento","2020","Este cuento relata el drama de una jovencita que se siente equivocadamente marginada, postergada por cuestiones raciales, su lucha íntima con los traumas y la falta de autoestima. Un tema difícil en círculos donde existen personas con serios complejos de inferioridad y que los convierten en seres que excluyen, critican y cuestionan a los hombres por su color. Esta narración, ayuda al lector a comprender bien que no existe razones válidas para considerar a las personas por su color, como más o menos aptas que las otras, asimismo inculca a ser inclusivos y solidarios.",9,"img/Mujer_9_Libro11.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(64,"Compadricha","9786125001047","Cuento","2020","La soledad de un hombre ya maduro, hace que éste reflexione sobre su vida de un modo sincero y sencillo con su mejor amigo, un perro también ya viejo; recuerda algunos sucesos de su juventud y que permite al lector evaluar la situación social de los campesinos hace años atrás y que de algún modo aún hoy pervive. Enseña la importancia de la reflexión y de aprender de las experiencias vividas.",9,"img/Mujer_9_Libro12.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(65,"El Curandero","97861250001054","Cuento","2020","Una serie de emergencias humanas, enfermedades y muertes por falta de auxilio oportuno, motivaran que una familia decida tomar una actitud y un cambio radical en sus activdades cotidianas, para bien para los pueblos ubicados en la selva.",9,"img/Mujer_9_Libro13.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(66,"Cuadernos incompletos",NULL,"Poemario","1969","Este poemario de Felix Flores Becerra esta acompañado de las ilustraciones de Emperatriz Escalante.",9,"img/Mujer_9_Libro14.jpg","Esta publicación no está disponible.",NULL),
	(67,"Lunas de ébano",NULL,"Poemario","2022","Podemos conceptualizar su trabajo en la expresión de 
la eternidad y de las cosas, seres y fenómenos de la naturaleza, pues aluden a su hija y 
a su madre, al Amazonas, a Cashiri (la luna masculina de los Ashaninka), a Machu Picchu…, que son también elementos propios de nuestro paisaje interior —y también del 
entorno cosmogeoecológico.",10,"img/Mujer_10_Libro1.jpg","Directamente con la autora","https://www.facebook.com/inakapalla.chavezbermudez"),
	(68,"Ellas: tejiendo historias desde el hilo rojo","9796114125181","Libro de investigación","2021","En esta serie de historias de mujeres cusqueñas Ellas, tejiendo historias desde el hilo
rojo, se reflexiona y evidencia el coraje y determinación de las mujeres del pasado al
defender sus ideales de justicia y libertad que abrieron camino a millones de peruanas
para luchar frente a las violencias de género.",10,"img/Mujer_10_Libro2.jpg","Drive","https://drive.google.com/file/d/1ZEHpW5isb-Wl1SlOi4rFeSYfADVj3bK4/view?usp=sharing"),
	(69,"Series de columnas en PULSO REGIONAL",NULL,"Columna","2019-2021","Un conjunto de 17 articulos dentro de la revista PULSO REGIONAL, los tópicos que resaltan son el arte, la litearuta, la investigación entre otros.",10,"img/Mujer_10_Libro3.jpg","PULSO REGIONAL","https://www.pulsoregional.pe/category/inakapalla-chavez/"),
	(70,"Eulogio Nishiyama y su acervo fotográfico del Cusco",NULL,"Articulo de revista","2019","Iñakapalla realiza un articulo en la revista “ Patrimonio N° 17” de marzo del 2019.",10,"img/Mujer_10_Libro4.jpg","Patrimonio en Issuu","https://issuu.com/drccusco/docs/revista_patrimonio_17_ddc-c/24"),
	(71,"La Cultura desde todos los Puntos de Vista: Una propuesta de modelo de desarrollo cultural en Brasil aplicada en Perú 
(Análisis del Libro Ponto de Cultura: O Brasil de baixo para cima- Celio Turino)","2013-10990","Artículo de revista","2013","Pagina 8, Análisis del Libro Ponto de Cultura: O Brasil de baixo para cima- Celio Turino por parte de Iñakapalla Chávez.",10,"img/Mujer_10_Libro5.jpg","Inkari Cultura","https://dokumen.tips/documents/revista-inkari-pdf.html?page=6"),
	(72,"Antologia de Poemas. Flora Tristan",NULL,"Antolgia","2012","Iñakapalla comparte algunos de sus poemas que aparecen en su poemario “Lunas de Añil”",10,"img/Mujer_10_Libro6.jpg","Pagina de Flora Tristan","http://www.flora.org.pe/poesia.htm"),
	(73,"Escenificación de Ceremonia Ancestral Wanakauri: La Política y la cultura van de la mano",NULL,"Columna","2010","Iñakapalla realiza esta columna en el diario: Diario el Sol del Cusco. En junio del 2010.",10,"img/Mujer_10_Libro7.jpg","Esta publicación no está disponible.",NULL),
	(74,"Biografía del fotógrafo cusqueño Eulogio Nishiyama",NULL,"Articulo de revista","2010","Iñakapalla realiza un articulo en la revista virtual “Gaseta Cultural Cusco“. Año 1, diciembre 2011.",10,"img/Mujer_10_Libro8.jpg","Gaseta Cultural Cusco en Issuu","https://issuu.com/art-restauro/docs/gacetaculturalcusco-diciembre2011"),
	(75,"Historia de la Moda cusqueña",NULL,"Columna","2008","Iñakapalla realiza esta columna en el diario: Diario el Sol del Cusco. En setiembre del 2008.",10,"img/Mujer_10_Libro9.jpg","Esta publicación no está disponible.",NULL),
	(76,"Los fotógrafos minuteros en Cusco",NULL,"Columna","2008","Colaboración en reportaje publicado en revista Somos del Diario El Comercio- Lima. Noviembre 2008.",10,"img/Mujer_10_Libro10.jpg","Esta publicación no está disponible.",NULL),
	(77,"Perú s. XXI. 60 poetas peruanos contemporáneos",NULL,"Antología","2007","Iñakapalla participa en esta antología realizada por la Escuela de Lima de Yacana Arte y Rock.",10,"img/Mujer_10_Libro11.jpg","Liberia del Sur","https://www.libreriasur.com.pe/libro/poesia-peru-s-xxi_123010"),
	(78,"La Makina de coser poemas",NULL,"Blog Personal","2007","Revista Online donde Iñakapalla realiza sus analisis de poesia y tambien comprate su creación Poetica, junto con algunos afiches de su autoria.",10,"img/Mujer_10_Libro12.jpg","BlogsPot","http://lamakinadecoserpoemas.blogspot.com/"),
	(79,"Lunas de Añil",NULL,"Poemario","2005","Los temas de su poesía son de manera muy marcada la luna y los sueños, está presente también el tema del amor. Otro tema muy fuerte es la necesidad imperiosa de escribir, necesidad que se presenta con deseo y pasión adictiva. Entre otros temas de su poesía son la soledad, la ciudad silente, en la que el yo poético siempre se dirige hacia el sur, el paso tan apresurado del tiempo y de los días, otro tópico clásico de la poesía.",10,"img/Mujer_10_Libro13.jpg","Esta publicación no está disponible.",NULL),
	(80,"Inti Raymi- Fiesta del Sol- Fundamentación documental del cuadro de Alfredo Rocha Segarra por el Dr. Manuel Chávez Ballón",NULL,"Libro de investigación","2016","En esta publicación es responsable de la investigación Iñakapalla Chávez Bermúdez y Ricardo Ráez Reátegui, en una reedición del trabajo de su abuelo Manuel Jorge Chávez Ballón.
",10,"img/Mujer_10_Libro14.jpg","Drive","https://drive.google.com/file/d/1Lhj2jDNUhCyViwhSuaTnafnE1AVzOueG/view?usp=sharing"),
	(81,"Liliana Davila Jurado",NULL,"Blog Personal","2022","El blog personal de Liliana Davila Jurado, esta constituido por distintos articulos sobre antropologia y algunos versos de la autora.",11,"img/Mujer_11_Libro1.jpg","BlogsPot","http://lidaju.blogspot.com/"),
	(82,"El Wayqui",NULL,"Libro de investigación","2015","El libro relata aspectos del hallazgo de la momia denominada El Wayqui, donde se pretende despertar el interés de los lectores en torno a temas de vida extraterrestre y posibles influencias en algunos aspectos culturales en la tierra. Este libro lo trabaja con su padre Renato Davila Riquelme en coautoria.",11,"img/Mujer_11_Libro2.jpg","Directamente con la autora","https://www.facebook.com/liliana.davilajurado.3"),
	(83,"Piedras Sagradas","DL 11723-2011-05804","Libro de investigación","2011","Publicación realizada por los antropólogos Renato Davila Riquelme y Liliana Davila Jurado, dicho libro muestra el trabajo previo que se realizó para la apertura del actual Museo Piedras Sagradas de Huaro; ubicación, aspectos museográficos, sociales, etc. Así como una interpretación de la iconografía hallada en cada petroglifo que hoy forman parte de Museo de sitio.",11,"img/Mujer_11_Libro3.jpg","Directamente con la autora","https://www.facebook.com/liliana.davilajurado.4"),
	(84,"Emiliano Huamantica
el sol rojo del Cusco","9786124864070","Biografia","2022","Cricia Ochoa Huamantica nos brinda una biografía que narra la historia de vida de Emiliano, desde sus años de infancia hasta su fatal accidente. Pero, sobre todo, nos ofrece un libro que hace un justo y merecido tributo a uno de los líderes sociales más importantes de nuestra historia. Finalmente, Emiliano Huamantica. El Sol Rojo del Cusco es también un reconocimiento a cada acto de lucha protagonizado por cientos de peruanos y peruanas en busca de un país mejor. Ninguno de aquellos acontecimientos debe ser condenado al olvido.",12,"img/Mujer_12_Libro1.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(85,"Emiliano Huamantica : biografía de un líder sindical",NULL,"Biografia","2016","El movimiento del proletariado peruano tiene sus propios paradigmas y héroes epónimos, en hombres que, habiendo nacido en la entraña misma del pueblo, llegaron a conducir los destinos de éste, con valentía y lucidez inigualables. Uno de estos hombres singulares fue el obrero textil Emiliano Huamantica Salinas",12,"img/Mujer_12_Libro2.jpg","Libreria Buho Azul","https://www.facebook.com/buhoazulcusco"),
	(86,"Ideario. 15 de mayo del 2020",NULL,"Columna","2020","Columna: Cusco, ciudad ecoamigable",12,"img/Mujer_12_Libro3.jpg","Ideario","https://es.calameo.com/read/0058691459435fcb7e7af?fbclid=IwAR1QfvBV8ulaUzJGx4z1MhmJeLbxboYzuGznKzSkRNrqJxd9oNuiX1o8k8Y"),
	(87,"Ideario 26. Revista semanal 16-21 setiembre 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: Bombardeemos Cusco",12,"img/Mujer_12_Libro4.jpg","Ideario","https://es.calameo.com/read/0058691450e04797d4c24"),
	(88,"Ideario 21. Revista semanal 12-18 agosto 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: ¿A dónde se fueron los incas?",12,"img/Mujer_12_Libro5.jpg","Ideario","https://es.calameo.com/read/0058691456c8f78551b7b"),
	(89,"Ideario 19.Revista semanal 19 julio- 4 de agosto 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: La fuerza del regueton",12,"img/Mujer_12_Libro6.jpg","Ideario","https://es.calameo.com/read/0058691454ee4b35c8507"),
	(90,"Ideario 13. Revista semanal 17-23 junio 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: El Cusco es ancho y ameno",12,"img/Mujer_12_Libro7.jpg","Ideario","https://es.calameo.com/read/005869145f4359f6b417b"),
	(91,"Ideario 11. Revista semanal 3-9 junio 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: De la cuestión de confianza y otros demonios",12,"img/Mujer_12_Libro8.jpg","Ideario","https://es.calameo.com/read/0058691451f2d59842626"),
	(92,"Ideario 7. Revista semanal 6-12 mayo del 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: Optimismo puro y duro",12,"img/Mujer_12_Libro9.jpg","Ideario","https://es.calameo.com/read/0058691459a0b2cd4f266?fbclid=IwAR05Tb3iynyPIlopacj3iRv2d62qs0Nfov51E40r_6qRED4ZyRxC-c81qQo"),
	(93,"Ideario 5. Revista semanal 22-28 abril del 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: ¿Qué es la vida, un frenesí?",12,"img/Mujer_12_Libro10.jpg","Ideario","https://es.calameo.com/read/005869145b5223a435fcc"),
	(94,"Ideario 3. Revista semanal 8-14 abril del 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: Mineroducto Las Bambas: Más falso que el floro de tu ex.",12,"img/Mujer_12_Libro11.jpg","Ideario","https://es.calameo.com/read/005869145e11202c0faed"),
	(95,"Ideario 1. Revista semanal 25-31 marzo 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo”: Crónica de un hospital anunciado",12,"img/Mujer_12_Libro12.jpg","Ideario","https://es.calameo.com/read/00586914545d65848464b?fbclid=IwAR3vMYYG-rdAguU0Rg9zlRQJHmtgSDFdjSTcfybemQOjQiP0q5XfQGJQOD0"),
	(96,"Ideario 0. Revista semanal 18 marzo 2019",NULL,"Columna","2019","Columna de opinión “Boquita de Caramelo” : ¿Por qué no existe un peruvian dream?",12,"img/Mujer_12_Libro13.jpg","Ideario","https://es.calameo.com/read/00586914592a32e73aa34?fbclid=IwAR2cfn9D6xazjI-1elkR1HaEvGcWUquJX8fg_5Va6k_xmrqlcoo730Xz7OQ"),
	(97,"Qosqo times",NULL,"Columna","2019","Columna de opinión politica de Cricia Ochoa",12,"img/Mujer_12_Libro14.jpg","Qosqo Times","https://qosqotimes.pe/category/columnas/cricia-ochoa/"),
	(98,"Tres poemas de Maggie Velarde",NULL,"Artículo de revista","2019","Aparicion en la Revista LUCERNA N°13, POESÍA",13,"img/Mujer_13_Libro1.jpg","Revista Lucerna","https://revistalucerna.com/2019/11/30/tres-poemas-de-maggie-ore/"),
	(99,"Breves Historias de los Efímeros",NULL,"Cuentos","2020","Libro de cuentos para niños acompañado de las ilustraciones de la autora.",13,"img/Mujer_13_Libro2.jpg","Esta publicación no está disponible.",NULL),
	(100,"Nueva poesía contemporánea: Maggie Velarde","2955-8131","Artículo de revista","2021","Aparicion en la Revista Kametsa",13,"img/Mujer_13_Libro3.jpg","Revista Kametsa","https://revistakametsa.wordpress.com/2021/04/27/nueva-poesia-contemporanea-maggie-velarde-peru/"),
	(101,"Poesía peruana: Maggie Velarde",NULL,"Artículo de revista","2021","Aparicion en Círculo de Poesía. Revista electrónica de literatura, año 12, No. 20, mayo 2020",13,"img/Mujer_13_Libro4.jpg","Círculo de Poesía","https://circulodepoesia.com/2021/10/poesia-peruana-maggie-velarde/"),
	(102,"El apu descalzo","9786124294310","Poemario","2021","En El apu descalzo, el apu, una de las principales deidades del mundo andino, se descalza y se hace carne, invocado por una voz sensible a los elementos de la naturaleza, pero también a lo incognoscible del destino y de la muerte, que se expresa con una poesía que rebasa el armazón estrófico convencional y se despliega sobre el infinito de la página en blanco, con una escritura caligramática de gran inventiva.",13,"img/Mujer_13_Libro5.jpg","La escencia","https://www.facebook.com/laesenciacusco"),
	(103,"POEMA: Trenzar",NULL,"Poema visual","2022","Este proyecto de poesía + video inició en pandemia, en medio de la soledad y la nostalgia de la tierra. Concluyó años después, luego de la tormenta. 
Se hizo para acompañarnos mediante el trenzado y la sororidad. Disfrute",13,"img/Mujer_13_Libro6.jpg","YouTube","https://www.youtube.com/watch?v=esOifLuUIVI"),
	(104,"El cuento peruano 2001-2010. 2 Vol","9786124202049","Antología","2013","Ricardo González Vigil reúne a 69 autores peruanos de diferentes estilos narrativos y agruparlos en dos tomos de colección. En este se ve la participación de Gabriela Caballero.",14,"img/Mujer_14_Libro1.jpg","Esta publicación no está disponible.",NULL),
	(105,"Narrativa en Tacna","9786124750335","Antología","2018","Un libro que trae una selección del proceso narrativo tacneño. Desde el siglo XVIII al XXI.",14,"img/Mujer_14_Libro2.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(106,"21. Relatos sobre la Independencia del Perú","9786124202490","Antología","2019","Los veintiún relatos sobre la Independencia del Perú fueron reunidos con el fin no de brindar una verdad histórica inmutable u oficial, sino de ofrecer diversas miradas, desde el plano de la verdad literaria, con todas las licencias que otorga el ejercicio de la ficción y la libre creación. Como suele ocurrir en esta clase de proyectos temáticos de narrativa, la dinámica misma de agruparlos garantiza un resultado superior a la suma de los efectos individuales. Esta tarea coordinada ha tenido una consecuencia no prevista, pero muy grata: cada cuento se circunscribe en el volumen como el capítulo de una novela que abarca un periodo de más de trescientos años, es decir, entre 1712 y 2018. El volumen cuenta con la participación de Fernando Iwasaki, Erika Almenara, Gabriela Caballero, Víctor Coral, Carlos Enrique Freyre, César Rosales-Miranda, Juan José Cavero, José Güich Rodríguez, Fabrizio Tealdo Zazzali, Harol Gastelú, Raúl Quiroz, María Lourdes Torres, Rosario Cardeña, Alejandro Neyra, Dante Castro, José Vadillo, Yelinna Pulliti, Ángel Málaga, Miguel Ángel Vallejo, Nataly Villena y Pedro Novoa.",14,"img/Mujer_14_Libro3.jpg","Petro Perú Gestión Cultural","https://cultura.petroperu.com.pe/biblioteca-cope/veintiun-relatos-volumen-uno/"),
	(107,"Mario y los escribidores: 27 relatos sobre el universo vargasllosiano","9786124420368","Antología","2019","Esta antología es un conjunto de relatos que plantea un interesante diálogo narrativo con uno de los mayores referentes de la literatura mundial. Pero eso no es todo, un particular bonus track y un dossier de tebeos (cada uno basado en una obra teatral del Nobel peruano) complementan lúdicamente esta suerte de tributo a uno de los peruanos más controvertidos de nuestra historia reciente",14,"img/Mujer_14_Libro4.jpg","Ediciones Altazor","https://www.facebook.com/ediciones.altazor/"),
	(108,"CUENTOS PERUANOS DE LA PANDEMIA","9786124554674","Antología","2021","El libro, más allá del intento de capturar el sentir del momento en la voz de nuestros creadores, funciona muy bien como un catálogo de la narrativa que se practica en nuestro país, su variedad de estilos y motivaciones. En sus casi 500 páginas se alternan cuentos de Gabriela Caballero, Teresa Ruiz Rosas, Alexis Iparraguirre, Fietta Jarque, Alejandro Neyra y más (en total, son 36).",14,"img/Mujer_14_Libro5.jpg","Librería Communitas","https://www.communitas.pe/es/peru/102680-cuentos-peruanos-de-la-pandemia-9786124554674.html"),
	(109,"Los relojes de Adela","9786124750359","Cuentos","2009","Colección de diez cuentos. La llegada de un profesor que, enfrentando a los personajes, inexplicablemente construye una escuela en un pueblo sin niños. El conflicto de un hombre que se descubre sin memoria y preso en una habitación extraña. La angustia de un joven, sufriendo el acoso y la presencia inquietante de tres hombres. La prolongada espera de una mujer aguardando el retorno de quien literalmente le ha dejado en prenda su corazón. Un grupo de muchachos enamorados de una joven que está muriendo, decididos a protegerla de la inminente venida de los otros. Un anciano que olvida un suceso importante. Una historia de amor que trastorna la racionalidad de una mujer. La llegada periódica de fotografías que exhiben la lenta agonía de una niña. El homicidio de una bella mujer en la playa. Y la historia de Adela y sus innumerables relojes incapaces de señalar la hora. Cuentos entretejidos en torno a la soledad, el intimismo, la incomunicación, los celos y el amor; bajo la perspectiva de lo fantástico. 
",14,"img/Mujer_14_Libro6.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(110,"Historias de arena: Cuentos playeros de Tacna",NULL,"Antología","2012","Antología de cuentos reunidos por el editor:William Gonzales, entre los autores que participan en esta publicación tenemos a W. Lizarraga, A. Paucar, J. Torres, A. Gamez, Gabriela Caballero entre otros.",14,"img/Mujer_14_Libro7.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(111,"Santiago","9786124750304","Novela","2017","A ritmo de vértigo y con un estilo marcadamente poético, se va narrando el viaje de un hombre sin memoria a bordo de un tren. Este viaje sirve de hilo conductor para ir desenvolviendo progresivamente el tránsito épico del protagonista hacia la soledad o la locura, la búsqueda del sentido de humanidad, la desintegración del núcleo familiar, la sucesión de hechos aciagos en un pueblo que irá anulándose. Todo ello asociado ineluctablemente a la extrañeza del personaje.",14,"img/Mujer_14_Libro8.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(112,"Poentos","9786124850509","Corrección de estilo","2021","Gabriela Caballero Delgado colabora en esta publicación como correctora de estilo. Sinopsis: Víctor Valqui en sus Poentos confirma su talento ya conocido como artista de poesía visual, su versatilidad y originalidad como escritor. Poentos es un libro que se disfruta y la experiencia reportada queda rondando en la memoria y nos alegra y nos enternece haciendo, por algunos momentos, blanca el alma del lector; al menos eso es lo que me ha pasado a mí, espero que sea así con usted amigo lector.",14,"img/Mujer_14_Libro9.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(113,"El sueño de Ícaro","9786124750397","Corrección de estilo","2021","Gabriela Caballero Delgado colabora en esta publicación como correctora de estilo. Sinopsis: El sueño de Ícaro es el poemario perdido del desaparecido Luis Chambilla Herrera. Una obra que luego de descubrirlo en medio de los papeles que alguna vez entregó a su amigo William Gonzalez sale a la luz tal como el autor lo dejó. Vuelve el poeta Chambilla a mostrarnos por qué es un referente en la poesía peruana del 2000 con sus versos que mantienen el ritmo cadencioso tan característico en su poesía.",14,"img/Mujer_14_Libro10.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(114,"Cantos de sombra y luz","9786124750380","Corrección de estilo","2021","Gabriela Caballero Delgado colabora en esta publicación como correctora de estilo. Sinopsis:“Cantos de sombra y luz” de Ingrid Caffera poemario ganador del XIV Concurso Nacional de Poesía “Horacio”, 2004, uno de cuyos jurados fue nuestro recordado José Watanabe, resulta sobrecogedor y exultante. No solo porque los conflictos de siempre que atenazan a los hombres (¿o, mejor, debería decir a las mujeres?): el amor, la soledad, el deseo, el desencanto, la esperanza… en las mujeres por razones de trasnochado machismo, forman parte de manera indeleble de aquello que los alemanes llaman el das Ewig-Weibliche o el eterno femenino, como si a los hombres, por razones únicas de serlo, no lo afectaran por igual.",14,"img/Mujer_14_Libro11.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(115,"Dios, el monje y la diva","9786124850516","Corrección de estilo","2021","Gabriela Caballero Delgado colabora en esta publicación como correctora de estilo. Sinopsis: Una historia que combina la política, el amor, la vida de un poeta y la guerrilla del MIR.
Juan Torres Gárate vuelve a mostrar su maestría en esta nueva obra que dejará al lector noqueado.",14,"img/Mujer_14_Libro12.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/"),
	(116,"La viuda negra","9786124750373","Corrección de estilo","2021","Gabriela Caballero Delgado colabora en esta publicación como correctora de estilo. Sinopsis: Yessira Kolaróv nunca tuvo momentos de paz en su vida. Todos sus recuerdos estaban plagados de situaciones difíciles que había empezado a olvidar casi involuntariamente, como si fuese una reacción instintiva para poder seguir viviendo sin perder la razón en el intento. Sin embargo, transcurrido algún tiempo, los recuerdos volvían. Se escabullían en su mente, cual pesadillas. La atacaban a ultranza y sin compasión. Ella llegó a creer que sus evocaciones cobraban vida propia y la arrastraban de nuevo al pasado, hundiéndola en aquella vorágine que siempre, desde niña, había sido su existencia, como si la introdujeran en una máquina maldita del tiempo.",14,"img/Mujer_14_Libro13.jpg","Cuadernos del Sur","https://www.facebook.com/CuadernosDelSur/");

INSERT INTO site_web_ejerce(id,mujer_id,categoria) VALUES
	(1,1,"Il"),
	(2,1,"Es"),
	(3,1,"Co"),
	(4,2,"Po"),
	(5,2,"Es"),
	(6,3,"Hi"),
	(7,3,"Ed"),
	(8,4,"Po"),
	(9,5,"Il"),
	(10,6,"Es"),
	(11,6,"Ed"),
	(12,6,"Cr"),
	(13,6,"Tr"),
	(14,7,"Es"),
	(15,8,"Po"),
	(16,9,"Es"),
	(17,9,"Il"),
	(18,10,"Po"),
	(19,10,"Es"),
	(20,10,"Cl"),
	(21,11,"Es"),
	(22,11,"An"),
	(23,11,"Po"),
	(24,12,"Es"),
	(25,12,"Cl"),
	(26,13,"Il"),
	(27,13,"Po"),
	(28,14,"Es"),
	(29,14,"Cr");
