DELETE FROM site_web_mujer;
DELETE FROM site_web_lugar;
DELETE FROM site_web_publicacion;
DELETE FROM site_web_ejerce;

INSERT INTO site_web_mujer(id,nombre,apellido,lugar_id,fecha_nacimiento,fecha_defuncion,coordx,coordy,trayectoria,link_imagen,contacto,entrevista) VALUES
	(1,"Adriana Hiromi ","Cule Vargas",50,"20/04/1996",NULL,"-13.518936101916335 ","-71.98050471302038","Adriana Cule es una artista visual y retratista profesional. Se desenvuelve en el terreno del diseño gráfico, el modelado análogo y digital, el desarrollo de personajes pintorescos y la creación de cuentos cortos. En susobras busca que las perspectivas y composición interactúen con el espectador exagerando las formas.
Ha participado en diferentes proyectos, muestras artísticas, diferentes campañas y producciones entre ellas la inauguración de Saga Falabella en Cusco, la filmación de Transformers en Cusco y la iniciativa de “Hagamos un Perú que de gusto” de Inca Kola.
Ilustro el cuento “El zorro y el cóndor” de Maximo Ccama, realizo el libro de cuentos “Sueño Índigo”  y los cómics “Pasado” y “Colores”.","img/Mujer_1.jpg","yozoh2004@gmail.com
",NULL),
	(2,"Ana Maria","Milla Hurtado",53,"15/06/1977",NULL,"-13.521690067304878 ","-71.95836371790017","Cusqueña de nacimiento, administradora de formación. Desde el 2003 ha participado como gestora cultural como productora de eventos y posteriormente la primera agenda cultural virtual, Agenda Cusco. Tiene trayectoria de empresaria turística del 2002, como diseñadora y productora de eventos durante 9 años. Ha participado en numerosos recitales, como poeta y productora. Actualmente dirige el Planetarium Cusco, centro de interpretación cultural, planetario y observatorio, lugar donde se difunde la ciencia, el universo y la astronomía cultural de los inkas. Es también feliz de mamá de tres y artista floral","img/Mujer_5.jpg","anamaria@planetariumcusco.com",NULL),
	(3,"Angela María"," Concha Pacheco",53,"06/06/1980",NULL,"-13.521690067304878 ","-71.95836371790017","Angela M. Concha es licenciada en Historia por la Universidad Nacional de San Antonio Abad del Cusco. Magister en Historia de América Latina, Mundos Indígenas por la Universidad Pablo de Olavide en Sevilla-España, y candidata a Doctora en Historia y Estudios Humanísticos: Europa, América, Arte y Lenguas por la misma Universidad. Con experiencia en trabajos sobre patrimonio documental y monumental (templos, casonas coloniales, centros arqueológicos y archivos históricos), en labores de conservación, catalogación e investigación. Docente de la Universidad de Salamanca (España)/ International Studies Abroad (ISA-Cusco) y de la Universidad Nacional de San Antonio Abad del Cusco.
","img/Mujer_6.jpg","angelamaria11y6@gmail.com",NULL);

INSERT INTO site_web_lugar(id,region,provincia,distrito) VALUES
	(1,"Cusco","Acomayo","Acomayo"),
	(2,"Cusco","Acomayo","Acopia"),
	(3,"Cusco","Acomayo","Acos"),
	(4,"Cusco","Acomayo","Mosoc Llacta"),
	(5,"Cusco","Acomayo","Pomacanchi"),
	(6,"Cusco","Acomayo","Rondocan"),
	(7,"Cusco","Acomayo","Sangarará"),
	(8,"Cusco","Anta","Ancahuasi"),
	(9,"Cusco","Anta","Anta"),
	(10,"Cusco","Anta","Cachimayo"),
	(11,"Cusco","Anta","Chinchaypujio"),
	(12,"Cusco","Anta","Huarocondo"),
	(13,"Cusco","Anta","Limatambo"),
	(14,"Cusco","Anta","Mollepata"),
	(15,"Cusco","Anta","Pucyura"),
	(16,"Cusco","Anta","Zurite"),
	(17,"Cusco","Calca","Calca"),
	(18,"Cusco","Calca","Coya"),
	(19,"Cusco","Calca","Lamay"),
	(20,"Cusco","Calca","Lares"),
	(21,"Cusco","Calca","Pisac"),
	(22,"Cusco","Calca","San Salvador"),
	(23,"Cusco","Calca","Taray"),
	(24,"Cusco","Calca","Yanatile"),
	(25,"Cusco","Canas","Checca"),
	(26,"Cusco","Canas","Kunturkanki"),
	(27,"Cusco","Canas","Langui"),
	(28,"Cusco","Canas","Layo"),
	(29,"Cusco","Canas","Pampamarca"),
	(30,"Cusco","Canas","Quehue"),
	(31,"Cusco","Canas","Tupac Amaru"),
	(32,"Cusco","Canas","Yanaoca"),
	(33,"Cusco","Canchis","Checacupe"),
	(34,"Cusco","Canchis","Combapata"),
	(35,"Cusco","Canchis","Marangani"),
	(36,"Cusco","Canchis","Pitumarca"),
	(37,"Cusco","Canchis","San Pablo"),
	(38,"Cusco","Canchis","San Pedro"),
	(39,"Cusco","Canchis","Sicuani"),
	(40,"Cusco","Canchis","Tinta"),
	(41,"Cusco","Chumbivilcas","Capacmarca"),
	(42,"Cusco","Chumbivilcas","Chamaca"),
	(43,"Cusco","Chumbivilcas","Colquemarca"),
	(44,"Cusco","Chumbivilcas","Livitaca"),
	(45,"Cusco","Chumbivilcas","Llusco"),
	(46,"Cusco","Chumbivilcas","Quiñota"),
	(47,"Cusco","Chumbivilcas","Santo Tomas"),
	(48,"Cusco","Chumbivilcas","Velille"),
	(49,"Cusco","Cusco","Ccorca"),
	(50,"Cusco","Cusco","Cusco"),
	(51,"Cusco","Cusco","Poroy"),
	(52,"Cusco","Cusco","San Jerónimo"),
	(53,"Cusco","Cusco","San Sebastián"),
	(54,"Cusco","Cusco","Santiago"),
	(55,"Cusco","Cusco","Saylla"),
	(56,"Cusco","Cusco","Wanchaq"),
	(57,"Cusco","Espinar","Alto Pichigua"),
	(58,"Cusco","Espinar","Condoroma"),
	(59,"Cusco","Espinar","Coporaque"),
	(60,"Cusco","Espinar","Espinar"),
	(61,"Cusco","Espinar","Ocoruro"),
	(62,"Cusco","Espinar","Pallpata"),
	(63,"Cusco","Espinar","Pichigua"),
	(64,"Cusco","Espinar","Suyckutambo"),
	(65,"Cusco","La Convención","Echarati"),
	(66,"Cusco","La Convención","Huayopata"),
	(67,"Cusco","La Convención","Inkawasi"),
	(68,"Cusco","La Convención","Kimbiri"),
	(69,"Cusco","La Convención","Maranura"),
	(70,"Cusco","La Convención","Megantoni"),
	(71,"Cusco","La Convención","Ocobamba"),
	(72,"Cusco","La Convención","Pichari"),
	(73,"Cusco","La Convención","Quellouno"),
	(74,"Cusco","La Convención","Santa Ana"),
	(75,"Cusco","La Convención","Santa Teresa"),
	(76,"Cusco","La Convención","Vilcabamba"),
	(77,"Cusco","La Convención","Villa Kintiarina"),
	(78,"Cusco","La Convención","Villa Virgen"),
	(79,"Cusco","Paruro","Accha"),
	(80,"Cusco","Paruro","Ccapi"),
	(81,"Cusco","Paruro","Colcha"),
	(82,"Cusco","Paruro","Huanoquite"),
	(83,"Cusco","Paruro","Omacha"),
	(84,"Cusco","Paruro","Paccaritambo"),
	(85,"Cusco","Paruro","Paruro"),
	(86,"Cusco","Paruro","Pillpinto"),
	(87,"Cusco","Paruro","Yaurisque"),
	(88,"Cusco","Paucartambo","Caicay"),
	(89,"Cusco","Paucartambo","Challabamba"),
	(90,"Cusco","Paucartambo","Colquepata"),
	(91,"Cusco","Paucartambo","Huancarani"),
	(92,"Cusco","Paucartambo","Kosñipata"),
	(93,"Cusco","Paucartambo","Paucartambo"),
	(94,"Cusco","Quispicanchi","Andahuaylillas"),
	(95,"Cusco","Quispicanchi","Camanti"),
	(96,"Cusco","Quispicanchi","Ccarhuayo"),
	(97,"Cusco","Quispicanchi","Ccatcca"),
	(98,"Cusco","Quispicanchi","Cusipata"),
	(99,"Cusco","Quispicanchi","Huaro"),
	(100,"Cusco","Quispicanchi","Lucre"),
	(101,"Cusco","Quispicanchi","Marcapata"),
	(102,"Cusco","Quispicanchi","Ocongate"),
	(103,"Cusco","Quispicanchi","Oropesa"),
	(104,"Cusco","Quispicanchi","Quiquijana"),
	(105,"Cusco","Quispicanchi","Urcos"),
	(106,"Cusco","Urubamba","Chinchero"),
	(107,"Cusco","Urubamba","Huayllabamba"),
	(108,"Cusco","Urubamba","Machupicchu"),
	(109,"Cusco","Urubamba","Maras"),
	(110,"Cusco","Urubamba","Ollantaytambo"),
	(111,"Cusco","Urubamba","Urubamba"),
	(112,"Cusco","Urubamba","Yucay");

INSERT INTO site_web_publicacion(id,titulo,isbn,categorizacion,fecha,descripcion,mujer_id,link_imagen,titulo_disponible,link_disponible) VALUES
	(1,"Sueño Indigo","9786124751028","Libro","2018","Libros que contiene dos historias tiernas, acompañadas de espectaculares ilustraciones que te transportarán junto a los protagonistas.",1,"img/Mujer_1_Libro1.jpg",NULL,"buhoazulcusco@gmail.com"),
	(2,"Colores",NULL,"Cómic","2020","La autora nos cuenta una pequeña anécdota de su infancia en el jardín de su abuela.",1,"img/Mujer_1_Libro2.jpg",NULL,"https://www.behance.net/gallery/125265469/COLORS-COMIC-Colores-Comic"),
	(3,"Pasado",NULL,"Cómic","2021","Cómic Ganador del Concurso Internacional de Historieta “La sociedad en tiempos de Pandemia” del Festival Virtual Internacional de las artes “Qosqo T’ikarinampaq 2020” Organizado por la Municipalidad del Cusco.",1,"img/Mujer_1_Libro3.jpg",NULL,"https://www.behance.net/gallery/124964849/PASADO-por-Adriana-Cule-AKA-Madivera"),
	(4,"Documentos para la historia eclesiástica de Apurímac. Análisis histórico al documento de la peregrinación de Sebastián Quimichi, siglo XVII","27098680","Articulo de revista","2020","El presente trabajo analiza la peregrinación de Sebastián “Quimichi”, a partir de la documentación que pertenece al archivo histórico del Santuario de Cocharcas, específicamente al documento denominado “Relación de la imagen de Nuestra Señora que esta en este pueblo de Cocharca hecha por el licenciado don Pedro Guillén de Mendoza en 20 de julio de 1625 años”.",3,"img/Mujer_6_Libro1.jpg","Revista Riqch’ariy Vol. 1, N° 01, 2020. pp. 147-178","https://www.academia.edu/44910438/REVISTA_RIQCH_ARIY_No_01"),
	(5,"El archivo del Santuario de Cocharcas: historia, catalogación y transcripción paleográfica siglos XVI-XX.","287307","Articulo de revista","2017","El motivo del presente trabajo es la difusión de los fondos documentales del Archivo Histórico del Santuario de Cocharcas, cuya recuperación y organización se inició el 2009 a través del entonces Instituto Nacional de Cultura Cusco (INC), institución que se encontraba restaurando el citado santuario. Con el trabajo efectuado, que fue la Puesta en Valor del archivo, se logró poner al servicio libros de cofradías, fábrica, inventarios, empadronamientos, testamentos y libros sacramentales (entierros, bautizos, matrimonios y confirmaciones), además de libros de inicios del siglo xx como litigación de tierras, peticiones y solicitudes, entre otros, que dan cuenta de la vida social, religiosa y cultural del santuario y la doctrina de Cocharcas, desde finales del siglo XVI hasta inicios del XX.",6,"img/Mujer_6_Libro2.jpg","Revista del Archivo General de la Nación N°32, 2017, págs. 287-307","https://revista.agn.gob.pe/ojs/index.php/ragn/issue/view/1/4"),
	(6,"Espacios de inclusión y exclusión: Etnias, ayllus y cofradías en la conformación de la doctrina eclesiástica de Cocharcas 1570-1614.","9786124544637","Articulo de revista","2013","El presente artículo se enmarca en el difícil proceso de reorganización social y religiosa que las poblaciones indígenas padecieron dentro de la región de Huamanga en la coyuntura finisecular del siglo XVI. Nuestra preocupación por comprender dichas reorganizaciones obedece a un doble interés, primero dar cuenta de la conformación del espacio social de la doctrina de Cocharcas, y segundo realizar un análisis de las relaciones interétnicas y las nociones de inclusión/exclusión a partir de la implantación de la institución de la cofradía, convirtiéndose en el medio de mayor eficacia para canalizar y viabilizar los intereses colonial étnicos locales de poder para así ganarse un espacio dentro de la nueva sociedad colonial que se conformaba.",6,"img/Mujer_6_Libro3.jpg","Cuadernos de Investigación Universitaria, 2013, núm. 01. 01 págs. 45-70","https://www.academia.edu/44912519/CUADERNOS_DE_INVESTIGACI%C3%93N_N_01"),
	(7,"El Santuario de Cocharcas: Construcción, clero secular y participación indígena (1611-1680)",NULL,"Articulo de revista","2013","El presente artículo se enmarca en el difícil proceso de reorganización social y religiosa que las poblaciones indigenas padecieron dentro de la región de Huamanga en la coyuntura finissecular del siglo XVI. Nuestra preocupación por comprender dichas reorganizaciones obdece a un doble interes, primero dar cuenta de la conformacipn del espacio social de la doctrina de Chocharcas, y segundo realziar un analisis de las relaciones interétnicas y las nociones de inclusión/exclusión apartir de la implementación de la cofradía, convirtiéndose en el medio de mayor eficacia para canalizar y viabilizar los intereses colonial étnicos locales de poder para así ganarse un espacio dentro de la nueva sociedad colonial que se conformaba.",6,"img/Mujer_6_Libro4.jpg","Arquitextual N°02, Huancayo, Diciembre 2013, pp 82-102.","https://issuu.com/gusstockconchaflores/docs/arquitextual_2"),
	(8,"Investigación histórica del Santuario de Cocharcas y el Archivo Arzobispal de Abancay.",NULL,"Articulo de revista","2014",NULL,3,"img/Mujer_6_Libro5.jpg",NULL,"http://archivosybibliotecasdelperu.blogspot.com/2014/03/investigacion-historica-del-santuario_1784.html"),
	(9,"RIQCH´ARIY",NULL,"Edición","2006, 2008, 2020, 2021","Revista de corte social con carácter multidisciplinario producido por el círculo de estudios del mismo nombre pertenecientes a la Facultad de Ciencias Sociales de la Universidad Nacional de San Antonio Abad del Cusco (UNSAAC).",3,"img/Mujer_6_Libro6.jpg",NULL,"https://revistariqchariy.com/"),
	(10,"CUADERNOS DE INVESTIGACIÓN UNIVERSITARIA",NULL,"Edición","2012, 2013, 2014","Revista exclusivo para jóvenes y egresados de las diversas carreras profesionales, con el objetivo de dar a conocer los resultados de las investigaciones científicas y los procesos de transferencia tecnológica que se da en la Universidad de San Antonio Abad del Cusco (UNSAAC)",3,"img/Mujer_6_Libro7.jpg",NULL,NULL),
	(11,"II SEMANA DE INVESTIGACIÓN",NULL,"Edición","2014","Publicación que conjuga un conjunto de actividades de capacitación y promoción de la investigación científica con el objetivo de generar un espacio plural de debate en relación a la invención, innovación e investigación científica, tecnológica y humanista en la región Cusco con participación de expertos, profesores y estudiantes universitarios de la UNSAAC y el país.",3,"img/Mujer_6_Libro8.jpg",NULL,NULL),
	(12,"VADEMECUM",NULL,"Edición","2013-2014","El Vicerrectorado de Investigación de la Universidad Nacional de San Antonio Abad del Cusco presenta la publicación VADEMÉCUM DE INVESTIGACIÓN FEDU 2013-2014, que da continuidad a la difusión de las diferentes investigaciones realizadas por grupos de docentes activos y jubilados durante el bienio señalado, los mismos fueron financiados con el Fondo Especial de Desarrollo Universitario (FEDU)",3,"img/Mujer_6_Libro9.jpg",NULL,"http://vrin.unsaac.edu.pe/publicaciones/1/vademecum-fedu-20132014.html"),
	(13,"Antología Angeles y Demonios",NULL,"Cuentos","1998","Antologia organziada por la Asociación Centro Cultural Cusco",2,"img/Mujer_5_Libro1.jpg",NULL,NULL),
	(14,"Poemario Acidulce","200901791","Poemario","2009","Éste es su primero poemario, como el título, un cúmulo de dulces y ácidas experiencias",2,"img/Mujer_5_Libro2.jpg",NULL,"https://anamaria.pro/acidulce/"),
	(15,"Mil Poemas a Cesar Vallejo: Una gesta de amor universal",NULL,"Poemario","2012","Ana María Milla participa en esta antologia con su poema en la pagina 349",2,"img/Mujer_5_Libro3.jpg",NULL,"https://spanport.byu.edu/instituto_vallejiano/documents/Untitled.pdf"),
	(16,"La hija del bosque",NULL,"Poemario","2019","La Hija del Bosque es su segundo poemario, y el primero la colección El Retorno de los paganos, colección de publicaciones sobre el retorno a la naturaleza y el viaje interior que toma de pretexto de los viajes físicos hacia otra comprensión del mundo y del universo.",2,"img/Mujer_5_Libro4.jpg",NULL,"buhoazulcusco@gmail.com"),
	(17,"Poemic: El atardecer del fin del mundo",NULL,"Cómic","2019","Poemic, es una producción que busca fusionar un poema con el arte del cómic. Con el título El atardecer del Fin del Mundo, es un viaje épico en un mundo en guerra, hacia la esperanza de un mundo mejor. Magistralmente ilustrado por el equipo de Qosqomic, liderado por el artista Fabricio Rivas Mar.",2,"img/Mujer_5_Libro5.jpg",NULL,"https://anamaria.pro/poemic/");

INSERT INTO site_web_ejerce(id,mujer_id,categoria) VALUES
	(1,1,"Co"),
	(2,1,"Es"),
	(3,1,"Il"),
	(4,3,"Ed"),
	(5,3,"Es"),
	(6,2,"Po");
