DELETE FROM Mujer;
DELETE FROM Publicacion;
DELETE FROM Lugar;
DELETE FROM Ejerce;

INSERT INTO Mujer VALUES (1,"Iñakapalla","Chávez Bermúdez",1,"20/06/1986",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (2,"Rosa Augusta","Rivero Ricalde",1,"14/04/1907","01/10/1966",NULL,NULL);
INSERT INTO Mujer VALUES (3,"Inés Qorich'aska","Quispe Puma",2,"1990",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (4,"Aleyda","Cárdenas",NULL,"1987",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (5,"Silvia Rosa","Huamaní Quispe",3,"1982",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (6,"Gladys","Conde Camargo",1,"1982",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (7,"Ana María","Milla Hurtado",1,"1977",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (8,"Ch'aska Eugenia","Anka Ninawaman",3,"1973",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (9,"Tania","Castro",1,"1973",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (10,"Karina","Pacheco Medrano",1,"1969",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (11,"Carmen","Escalante Gutiérrez",1,"1953",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (12,"Ana Bertha","Vizcarra",1,"1947",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (13,"Mercedes","Delgado",1,"1939",NULL,NULL,NULL);
INSERT INTO Mujer VALUES (14,"Clorinda","Matto de Turner",1,"11/11/1852","25/10/1909",NULL,NULL);
INSERT INTO Mujer VALUES (15,"Adriana","Hiromi Cule",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (16,"Alfonsina","Barrionuevo",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (17,"Anael Nuit","Pilares Valdivia",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (18,"Areli","Aráoz",4,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (19,"Emperatriz","Escalante Gutiérrez",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (20,"Frida","Ibáñez Ayerbe",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (21,"Gladys","Conde",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (22,"Nataly","Villena",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (23,"Nohemi","Estrada Pérez",1,NULL,NULL,NULL,NULL);
INSERT INTO Mujer VALUES (24,"Tania Consuelo","Gutiérrez Samanez",1,NULL,NULL,NULL,NULL);

INSERT INTO Publicacion VALUES (1,"Teorías del reflejo","2018",NULL,4);
INSERT INTO Publicacion VALUES (2,"Ch'askaschay","2004",NULL,8);
INSERT INTO Publicacion VALUES (3,"T'ika chumpicha","2010",NULL,8);
INSERT INTO Publicacion VALUES (4,"1 al 20","1970",NULL,12);
INSERT INTO Publicacion VALUES (5,"Manual del guerillo","1971",NULL,12);
INSERT INTO Publicacion VALUES (6,"Machupicchu, orgasmo de piedra","2017",NULL,12);
INSERT INTO Publicacion VALUES (7,"Peces de betún","1969",NULL,13);
INSERT INTO Publicacion VALUES (8,"Sueño Indigo","2018",NULL,15);
INSERT INTO Publicacion VALUES (9,"Juego y silencio","2009",NULL,21);
INSERT INTO Publicacion VALUES (10,"Semillitas","2015",NULL,24);

INSERT INTO Lugar VALUES (1,NULL,NULL,"Cusco",NULL);
INSERT INTO Lugar VALUES (2,NULL,"Acomayo","Cusco",NULL);
INSERT INTO Lugar VALUES (3,NULL,"Espinar","Cusco",NULL);
INSERT INTO Lugar VALUES (4,"Limatambo","Anta","Cusco",NULL);

INSERT INTO Ejerce VALUES (1,7,"Es");
INSERT INTO Ejerce VALUES (2,8,"Po");
INSERT INTO Ejerce VALUES (3,8,"Tr");
INSERT INTO Ejerce VALUES (4,8,"Pr");
INSERT INTO Ejerce VALUES (5,10,"Es");
INSERT INTO Ejerce VALUES (6,10,"Ed");
INSERT INTO Ejerce VALUES (7,10,"An");
INSERT INTO Ejerce VALUES (8,14,"Es");
INSERT INTO Ejerce VALUES (9,14,"Ed");
INSERT INTO Ejerce VALUES (10,15,"Es");
INSERT INTO Ejerce VALUES (11,15,"Il");
INSERT INTO Ejerce VALUES (12,17,"Ed");
INSERT INTO Ejerce VALUES (13,19,"An");
INSERT INTO Ejerce VALUES (14,20,"Po");
INSERT INTO Ejerce VALUES (15,23,"Es");
